<div id="footer">
    <div class="footerbottom">
        <div class="container">
            <div class="row">
                <div class="col-xs-5"><span class="footervalign"><?= icms::site_com() ?> &copy; <?= date('Y') ?> - Her Hakkı Saklıdır.</span></div>
                <div class="col-xs-7"><img src="/img/footer-logo.jpg" width="467" height="29">
                    <a href="http://www.teknomavi.com" title="Bu sitenin e-ticaret altyapısı TeknoMavi tarafından geliştirilmiştir.">
                        <img class="pull-right" src="/img/teknomavi-logo.png" alt="TeknoMavi" width="50" height="29"></a>
                </div>
            </div>
        </div>
    </div>
</div>
<?= view::load_scripts() ?>
<?
if (!defined("DISABLE_TRACKERS")) {
    echo view::load("tracker/global_tracker");
}
?>
