<head>
    <title><?= view::get_title() ?></title>
    <meta charset="UTF-8">
    <meta name="web_author" content="TeknoMavi">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=1030">
    <?= view::get_header_tags() ?>
    <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico"/>
    <link rel="search" type="application/opensearchdescription+xml" href="/opensearchdescription.xml" title="<?= app::getName() ?>"/>
    <?= view::load_styles() ?>
    <?= view::load_scripts('jQuery') ?>
    <?= view::load_inline_scripts() ?>
    <!--[if lt IE 9]>
    <script type='text/javascript' src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script type='text/javascript' src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js"></script>
    <![endif]-->
</head>
