<?
/**
 * @var category_model[] $catalogs
 * @var category_model $category
 * @var string $navigationPills
 * @var string $navigationMessage
 */
?>
<div class="headerMenu">
    <div class="container">
        <div class="row">
            <div class="col-xs-3 openMenu">
                <div class="dropdownTitle"><a href="/" title="Tüm Kategoriler" class="has-sub"> TÜM KATEGORİLER <i class="glyphicon glyphicon-circle-arrow-down"></i></a></div>
                <ul class="dropdownOpener <?= (view::$menuOpenFirstLevel ? "openBlock" : "") ?>">
                    <? if (count($catalogs)) { ?>
                        <? foreach ($catalogs as $catalog) { ?>
                            <li>
                                <a href="<?= link::toCategory($catalog) ?>"><?= $catalog->category_name ?></a>
                                <? if (isset($childCategories[$catalog->category_id]) && count($childCategories[$catalog->category_id])) { ?>
                                    <div class="subMenuContent clearfix">
                                        <div class="subMenuItems">
                                            <span class="subMenuHeader"><?= icms::strtoupper($catalog->category_name) ?></span>
                                            <ul>
                                                <? foreach ($childCategories[$catalog->category_id] as $category) { ?>
                                                    <li><a href="<?= link::toCategory($category) ?>"><?= $category->category_name ?></a></li>
                                                <? } ?>
                                            </ul>
                                        </div>
                                    </div>
                                <? } ?>
                            </li>
                        <? } ?>
                    <? } ?>
                </ul>
                <!-- buraya menu gelecek -->
            </div>
            <div class="col-xs-9">
                <div class="navAds clearfix">
                    <? if (!empty($navigationPills)) { ?>
                        <div class="pull-left NavigationPills">
                            <?= $navigationPills ?>
                        </div>
                    <? } ?>
                    <? if (!empty($navigationMessage)) { ?>
                        <div class="pull-right NavigationMessage">
                            <?= $navigationMessage ?>
                        </div>
                    <? } ?>
                </div>
            </div>
        </div>
    </div>
</div>
