<?
/**
 * @var ob_basket $basket
 * @var array $checkFreeShipping
 * @var float $minInstallmentPrice
 */
?>
<div class="row cartPage">
    <div class="col-xs-8">
        <div class="shoppingCart mb">
            <h2>ALIŞVERİŞ SEPETİNİZ</h2>
            <div class="cartItemTitles">
                <div class="clearfix">
                    <div class="col-xs-8">Ürün</div>
                    <div class="col-xs-2 text-center">Fiyatı</div>
                    <div class="col-xs-2 text-center">Adet</div>
                </div>
            </div>
            <form id="cartUpdate" method="post" action="/basket/update/">
                <input type="hidden" name="form" value="cartUpdate"/>
                <?
                $packageCount = 0;
                $totalPackageCount = count($basket->packages);
                $productIds = array();
                $totalEarnings = 0;
                $divide = false;
                foreach ($basket->packages as $key => $package) {
                    $packageCount++;
                    foreach ($package->productData as $productData) {
                        $product = singleton::product($productData->productId);
                        $inStock = intval($product->warehouse_stock);
                        $productIds[] = $product->product_id;
                        ?>
                        <div class="clearfix mt cartOneProduct">
                            <div class="col-xs-2"><img src="<?= $product->getPhoto('catalog') ?>" width="98"></div>
                            <div class="col-xs-6"><a href="<?= $product->getUrl() ?>"><?= $product->full_name ?> </a>
                                <div class="productOption">
                                    <? if (in_array($product->product_id, $basket->opportunityProductIds)) { ?>
                                        <span class="label label-primary">FIRSAT ÜRÜNÜ</span>
                                    <? } ?>
                                    <? if ($inStock >= $productData->quantity && !$product->promoteCampaignId) { ?>
                                        <? if ($inStock <= 5) { ?>
                                            <span class="label label-warning">STOKTA SON <?= $inStock ?> ÜRÜN</span>
                                        <? } else { ?>
                                            <span class="label label-success">ÜRÜN STOKLARIMIZDA</span>
                                        <? } ?>
                                    <? } else {
                                        if ($product->leadTime() == 1) { ?>
                                            <span class="label label-success">24 SAATTE KARGODA!</span>
                                        <? } else { ?>
                                            <span class="label label-info"><?= $product->leadTime() ?> İŞ GÜNÜNDE KARGODA</span>
                                        <? }
                                    } ?>
                                </div>
                            </div>
                            <div class="col-xs-2 itemPrice text-center">
                                <div class="price"><?= icms::format_money($productData->price) ?></div>
                                <? if ($product->getBasePrice() > $productData->price) { ?>
                                    <div class="old"><?= icms::format_money($productData->basePrice) ?></div>
                                <? } ?>
                            </div>
                            <div class="col-xs-2 itemQuantity text-center">
                                <div class="productQuantity pull-left">
                                    <div class="input-group pull-left">
                                        <span class="input-group-btn"><button onclick="quantity('#qty-<?= $productData->productId ?>','down')" class="btn btn-default btn-xs"
                                                type="button">
                                                <i class="glyphicon glyphicon-minus"></i></button></span>
                                        <input type="text" id="qty-<?= $productData->productId ?>" data-ref="update<?= $productData->productId ?>"
                                            name="quantity[<?= $productData->productId ?>]" class="form-control input-xs quantity_input text-center" min="0"
                                            max="<?= $product->saleableProductCount() ?>" value="<?= $productData->quantity ?>" title="Ürün Adedi" onblur="quantity($(this))">
                                        <span class="input-group-btn"><button onclick="quantity('#qty-<?= $productData->productId ?>','up')" class="btn btn-default btn-xs"
                                                type="button">
                                                <i class="glyphicon glyphicon-plus"></i></button></span>
                                    </div>
                                </div>
                                <a href="javascript:" class="updateQuantityButton update<?= $productData->productId ?>" style="display:none;">Güncelle</a>
                                <a onclick="return confirm('Bu ürünü sepetinizden çıkarmak istediğinize emin misiniz?');" href="/basket/remove/<?= $productData->productId ?>">Sepetten
                                    Çıkart</a>
                            </div>
                        </div>
                    <? } ?>
                <? } ?>
            </form>
        </div>
        <div class="alert alert-info mb">
            <p>
                <? if ($basket->maxEstimatedShippingDate == date('Y-m-d')) { ?>
                    Siparişiniz, <strong>BUGÜN</strong> kargoya verilecektir.
                <? } else {
                    if ($basket->minEstimatedShippingDate == $basket->maxEstimatedShippingDate) { ?>
                        Sepetinizde <strong>Aynı Gün Kargo</strong> olmayan ürünler bulunuyor.<br> Siparişiniz tahminen
                        <strong><?= icms::format_date($basket->maxEstimatedShippingDate, true) ?></strong> tarihinde kargoya verilecektir.
                    <? } else { ?>
                        Sepetinizde <strong>Aynı Gün Kargo</strong> olmayan ürünler bulunuyor.<br> Siparişiniz tahminen
                        <strong><?= icms::format_date($basket->minEstimatedShippingDate, true) ?> - <?= icms::format_date($basket->maxEstimatedShippingDate,
                                true) ?></strong> tarihleri arasında  kargoya verilecektir.
                    <? }
                } ?>
            </p>
        </div>
    </div>
    <div class="col-xs-4">
        <? if ($basket->memberBalance > 0) { ?>
            <div class="orderBalance clearfix mb">
                <h2>HESAP ÖZETİNİZ</h2>
                <p><strong>Kullanılabilir Bakiye: <?= icms::format_money($basket->memberBalance) ?></strong></p>
                <p>Hesabınızdaki bakiyeyi "Ödeme Bilgileri" adımında kullanabilirsiniz.</p>
            </div>
        <? } ?>
        <div class="orderSummaryDetails clearfix mb">
            <h2>SİPARİŞ ÖZETİNİZ</h2>
            <? if ($basket->cargoPrice < $basket->defaultCargoPrice) { ?>
                <div class="orderArea pb5 mb5 clearfix">
                    <div class="col-xs-1"><i class="glyphicon glyphicon-ok-circle"></i></div>
                    <div class="col-xs-11">
                        <strong><?= ($basket->cargoPrice == 0 ? 'Ücretsiz' : 'İndirimli') ?> kargo</strong> fırsatından faydalanıyorsunuz.
                    </div>
                </div>
            <? } ?>
            <div class="orderArea pb5 mb5 clearfix">
                <div class="col-xs-6 text-right">Sepet Toplamı :</div>
                <div class="col-xs-6 text-left priceStrong"><?= icms::format_money($basket->sumSalePrice) ?></div>
            </div>
            <div class="orderArea pb5 mb5 clearfix">
                <div class="col-xs-6 text-right">Kargo Ücreti :</div>
                <div class="col-xs-6 text-left priceStrong">
                    <? if ($basket->cargoPrice < $basket->defaultCargoPrice) { ?>
                        <del><?= icms::format_money($basket->defaultCargoPrice) ?></del>
                    <? } ?>
                    <?= ($basket->cargoPrice > 0) ? icms::format_money($basket->cargoPrice) : 'Ücretsiz' ?>
                </div>
            </div>
            <? if ($basket->cargoPrice > 0 && $checkFreeShipping) { ?>
                <div class="orderArea pb5 mb5 clearfix">
                    <div class="col-xs-6 text-right">Fırsat :</div>
                    <div class="col-xs-6 text-left">Sepetine <b><?= icms::format_money($checkFreeShipping['amount']) ?></b>'lik ürün ekle, kargon
                        <?= ($checkFreeShipping['type'] == 'free' ? "ücretsiz" : "indirimli") ?> olsun
                    </div>
                </div>
            <? } ?>
            <? if ($basket->member_check_id > 0 && $basket->discountProductAmount > 0) { ?>
                <div class="orderArea pb5 mb5 clearfix">
                    <div class="col-xs-6 text-right">Alışveriş Çeki :</div>
                    <div class="col-xs-6 text-left priceStrong">- <?= icms::format_money($basket->discountProductAmount) ?></div>
                </div>
            <? } ?>
            <? if ($basket->coupon_id > 0 && $basket->discountProductAmount > 0) { ?>
                <div class="orderArea pb5 mb5 clearfix">
                    <div class="col-xs-6 text-right">Kupon Kodu :</div>
                    <div class="col-xs-6 text-left priceStrong">
                        - <?= icms::format_money($basket->discountProductAmount) ?>
                        <? if ($basket->promoteCoupon()->coupon_type == promote_coupons_model::COUPON_TYPE_PERCENT) {
                            $promoteCouponRules = json_decode($basket->promoteCoupon()->coupon_rule);
                            ?>
                            <br>
                            %<?= $promoteCouponRules->discount_amount ?> İndirim
                        <? } ?>
                    </div>
                </div>
            <? } ?>
            <div class="orderArea pb5 mb5 clearfix totalPrice text-center">
                <span>Ödenecek Tutar</span><br> <strong><?= icms::format_money($basket->sumAmount()) ?></strong>
                <div id="buyNowButton">
                    <a href="<?= app::getUrl(ACTIVE_APP, "https") ?>/checkout" type="button"
                        class="btn btn-warning Buy noiseBg <?= session::memberId() && !session::isAuthenticated() ? 'login-required' : '' ?>">Satın Al</a>
                </div>
                <div id="updateButton" style="display:none;">
                    <a href="javascript:" type="button" class="updateQuantityButton btn btn-warning Buy noiseBg">Sepeti Güncelle</a>
                </div>
            </div>
            <? if (!$basket->coupon_id && !$basket->member_check_id) { ?>
                <div class="orderArea pb5 mb5 clearfix couponCode">
                    <div class="col-xs-1"><i class="glyphicon glyphicon-tag"></i></div>
                    <div class="col-xs-11"><label for="coupon">Kupon kodunuz mu var?</label><br>
                        <div class="input-group">
                            <span class="input-group-btn"><button class="btn btn-warning btn-xs cartMiniButton" onclick="use_coupon();" type="button">KULLAN</button></span>
                            <input type="text" name="coupon" id="coupon" class="form-control input-xs">
                        </div>
                    </div>
                </div>
            <? } else {
                if ($basket->coupon_id) { ?>
                    <div class="orderArea pb5 mb5 clearfix couponCode">
                        <div class="col-xs-1"><i class="glyphicon glyphicon-tag"></i></div>
                        <div class="col-xs-11">Kullanmış olduğunuz kupon kodu<br>
                            <div class="input-group">
                                <span class="input-group-btn"><button class="btn btn-warning btn-xs cartMiniButton" onclick="use_coupon();" type="button">İPTAL</button></span>
                                <input type="text" name="coupon" id="coupon" class="form-control input-xs" value="" placeholder="<?= $basket->promoteCoupon()->coupon_code ?>">
                            </div>
                        </div>
                    </div>
                <? }
            } ?>
            <? if (!$basket->coupon_id) { ?>
                <div class="orderArea pb5 mb5 clearfix shoppingVouchers">
                    <div class="col-xs-1"><i class="glyphicon glyphicon-bookmark"></i></div>
                    <div class="col-xs-11"><label>Alışveriş çekinizi kullanmak ister misiniz?</label><br>
                        <a href="javascript:" id="shoppingChecks" type="button" class="btn btn-warning btn-xs cartMiniButton">KULLAN</a>
                    </div>
                </div>
            <? } ?>
            <? if ($minInstallmentPrice) { ?>
                <div class="orderArea pb5 mb clearfix financingOptions">
                    <div class="col-xs-1"><i class="glyphicon glyphicon-th"></i></div>
                    <div class="col-xs-11">
                        Bu siparişinizi <strong><?= icms::format_money($minInstallmentPrice) ?></strong> 'den<br>başlayan taksitlerle ödeyebilirsiniz. <br>
                        <a href="javascript:" id="installmentOptions" type="button" class="btn btn-warning btn-xs cartMiniButton">TAKSİT SEÇENEKLERİNİ GÖSTER</a>
                    </div>
                </div>
            <? } ?>
        </div>
    </div>
</div>
<script type="text/javascript">
    var qtyChanged = false;
    $(function () {
        $('.quantity_input').change(function () {
            qtyChanged = false;
            $("#buyNowButton").show();
            $("#updateButton").hide();
            $.each($('form#cartUpdate input.quantity_input'), function () {
                if ($(this).val() !== $(this).attr("value")) {
                    $("a." + $(this).data('ref')).show();
                    $("#buyNowButton").hide();
                    $("#updateButton").show();
                    qtyChanged = true;
                } else {
                    $("a." + $(this).data('ref')).hide();
                }
            });
            return true;
        });
        $(".updateQuantityButton").click(function () {
            if (qtyChanged) {
                $('form#cartUpdate').submit();
            }
        });
        $("#shoppingChecks").on("click", function () {
            $.get("/basket/getShoppingChecks", function (data) {
                $('body').append(data);
                $('.modal').modal('toggle')
            });
        });
        $("#installmentOptions").on("click", function () {
            $.get("/basket/installments", function (data) {
                $('body').append(data);
                $('.modal').modal('toggle')
            });
        });
    });
    function use_coupon() {
        $.ajax({
            type: "post",
            url: "/basket/use_coupon",
            data: {coupon: $('#coupon').val()},
            success: function (data) {
                if (!data) {
                    return alert('Kupon kodu kullanılırken hata oluştu');
                }
                if (data.Status && data.Status == 'OK') {
                    window.location = '/basket';
                    return true;
                }
                alert('Hatalı bir kupon kodu girdiniz');
            },
            error: function () {
                alert('Kupon kodu kullanılırken hata oluştu');
            }
        }).done(function () {
            window.location = '/basket';
        });
    }
</script>
