<?
/**
 * @var string $redirectTo
 */
?>
<div class="loginPage">
    <div class="mb socialLogin">
        <p class="mt text-center"><strong>Sosyal medya hesabınızı kullanarak <?= icms::site_com("a") ?> kolayca giriş yapabilirsiniz.</strong></p>
        <div class="mt text-center">
            <button type="submit" onclick="window.location='/member/oauth/facebook/?b64=<?= base64_encode($redirectTo) ?>'" class="btn btn-default buttonFacebook">Facebook ile
                Bağlan
            </button>
            &nbsp;
            <button type="submit" onclick="window.location='/member/oauth/google/?b64=<?= base64_encode($redirectTo) ?>'" class="btn btn-default buttonGooglePlus">Google+ ile
                Bağlan
            </button>
        </div>
        <br>
    </div>
    <div class="row">
        <div class="col-xs-4">
            <h2>Üye Girişi</h2>
            <div>
                <p class="mt text-center">E-Postanızı ve Parolanızı girerek giriş yapabilirsiniz.</p>
                <form method="post" action="<?= app::getUrl(ACTIVE_APP, "https") ?>/member/signin" role="form" id="login" class="form-horizontal">
                    <input type="hidden" value="<?= $redirectTo ?>" name="redirectTo">
                    <div class="form-group mt">
                        <div class="col-xs-10 col-xs-offset-1">
                            <label for="LoginEmail">E-Posta Adresiniz:</label> <input type="email" id="LoginEmail" class="form-control" onkeypress="return disableSpaceKey(event);"
                                name="email">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-10 col-xs-offset-1">
                            <label for="LoginPassword">Parolanız:</label> <input type="password" id="LoginPassword" class="form-control" name="password">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-10 col-xs-offset-1 text-left">
                            <button class="btn btn-warning noiseBg" type="submit">Giriş Yap</button>
                            <a href="/member/forgot_password" class="textButton">Parolamı Unuttum</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-xs-8">
            <h2>Üye Olmak İstiyorum</h2>
            <div>
                <p class="mt text-center">Sadece aşağıdaki bilgilerini vererek sitemizden alışveriş yapmaya başlayabilirsiniz.</p>
                <form method="post" action="<?= app::getUrl(ACTIVE_APP, "https") ?>/member/signup" role="form" id="registerForm" class="form-horizontal" novalidate="novalidate">
                    <input type="hidden" value="<?= $redirectTo ?>" name="redirectTo">
                    <div class="form-group mt">
                        <div class="col-xs-5 col-xs-offset-1"><label for="SignupName">Adınız:</label> <input type="text" id="SignupName" class="form-control" name="firstname">
                        </div>
                        <div class="col-xs-5"><label for="SignupSurname">Soyadınız:</label> <input type="text" id="SignupSurname" class="form-control" name="surname"></div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-5 col-xs-offset-1">
                            <label for="SignupEmail">E-Posta Adresi:</label> <input type="email" id="SignupEmail" class="form-control" onkeypress="return disableSpaceKey(event);"
                                name="email">
                        </div>
                        <div class="col-xs-5">
                            <label for="SignupPassword">Parola:</label> <input type="password" id="SignupPassword" class="form-control" name="passwd">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-10 col-xs-offset-1 text-left">
                            <div class="checkbox">
                                <label> <input type="checkbox" checked="checked" name="subscription" id="subscription">Kampanyalar ile ilgili e-posta mesajları almak
                                    istiyorum.</label>
                            </div>
                            <div class="mt">
                                <button class="btn btn-warning noiseBg" type="submit">Hesabımı Oluştur</button>
                            </div>
                            <div class="mt">
                                Hesap oluşturarak
                                <a data-target="#modalBox" data-toggle="modal" onclick="load_modal('/uyelik-sozlesmesi')" href="javascript:" class="b">üyelik sözleşmesini</a>
                                okuduğunuzu ve kabul ettiğinizi onaylıyorsunuz.
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="modalBox" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="modalLabel">Kullanım Koşulları ve Gizlilik Sözleşmesi</h4>
            </div>
            <div class="modal-body clearfix"></div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function load_modal(page) {
        $.post(page, {ajax: 1}, function (data) {
            $('.modal-body').html(data)
        });
    }
    $(function () {
        $('input[name=email]').blur(function () {
            $(this).val(function (i, oldval) {
                return $.trim(oldval);
            });
        });
        $("#registerForm").validate({
            rules: {
                email: {required: true, email: true},
                passwd: {required: true},
                firstname: {required: true, minlength: 2},
                surname: {required: true, minlength: 2}
            }
        });
    });
</script>
