<div class="row mt passReset">
    <div class="col-xs-8 col-xs-offset-2" style="min-height: 300px;">
        <div class="text-center">
            <i class="glyphicon glyphicon-lock mt mb bigRoundStamp"></i> <br/> Parolanızı değiştirmeniz için yapmanız gereken işlemleri e-posta adresinize göndereceğiz.
        </div>
        <form id="reminderForm" method="post">
            <input type="hidden" name="form" value="password-reminder"/>
            <div class="row mt">
                <div class="col-xs-6 col-xs-offset-3">
                    <div class="form-group">
                        <label for="email">E-Posta Adresiniz:</label> <input type="text" name="email" id="email" class="form-control" placeholder="E-Posta Adresiniz"
                            autocomplete="off">
                    </div>
                    <div class="form-group text-center">
                        <button class="btn btn-warning" type="submit">Parolamı Sıfırla <i class="glyphicon glyphicon-chevron-right"></i></button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        $("#reminderForm").validate({
            rules: {
                email: {required: true, email: true}
            }
        });
    });
</script>
