<div class="row mt passReset">
    <div class="col-xs-8 col-xs-offset-2" style="min-height: 300px;">
        <div class="text-center">
            <i class="glyphicon glyphicon-lock mt mb bigRoundStamp"></i> <br/> Parolanızı değiştirmeniz için yapmanız gereken işlemleri e-posta adresinize göndereceğiz.
        </div>
        <form id="resetForm" method="post">
            <input type="hidden" name="form" value="password-reset"/>
            <div class="row mt">
                <div class="col-xs-6 col-xs-offset-3">
                    <div class="form-group">
                        <label for="passwd">Yeni Parolanız:</label> <input type="password" class="form-control" id="passwd" name="passwd" autocomplete="off"
                            placeholder="Yeni Parolanızı Girin"/>
                    </div>
                    <div class="form-group">
                        <label for="repass">Yeni Parolanız (Tekrar):</label>
                        <input type="password" class="form-control" id="repass" name="repass" autocomplete="off" placeholder="Yeni Parolanızı Tekrar Girin"/>
                    </div>
                    <div class="form-group text-center">
                        <button class="btn btn-warning" type="submit">Parolamı Güncelle <i class="glyphicon glyphicon-chevron-right"></i></button>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        $("#resetForm").validate({
            rules: {
                passwd: {required: true},
                repass: {required: true, equalTo: "#passwd"}
            }
        });
    });
</script>
