<?
/**
 * @var string $id
 * @var string $title
 * @var string $content
 */
?>
<div class="modal fade" id="<?= $id ?>" tabindex="-1" role="dialog" aria-labelledby="<?= $id ?>Label" aria-hidden="true">
    <div class="modal-dialog <?= (isset($class) ? $class : "") ?>">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="<?= $id ?>Label"><?= $title ?></h4>
            </div>
            <div class="modal-body clearfix">
                <?= $content ?>
            </div>
        </div>
    </div>
</div>
