<?
/**
 * @var ob_order $order
 * @var int      $orderId
 * @var array    $productIds
 * @var bool     $firstOrder
 * @var string   $orderCode
 * @var float    $orderTotalAmount
 * @var float    $orderTotalTax
 * @var array    $channelData
 */
?>
<? /* START Google Adwords */ ?>
<? if (\TeknoETicaret\Config\Settings::get('adwords.remarketing.enabled')) { ?>
    <!-- Google Code for Dönüşümler Conversion Page -->
    <script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = <?= \TeknoETicaret\Config\Settings::get('adwords.remarketing.conversionid') ?>;
        var google_conversion_language = "en";
        var google_conversion_format = 3;
        var google_conversion_color = "ffffff";
        var google_conversion_label = "BMP4CNK31VwQjoag-AM";
        var google_conversion_value = <?=$orderTotalAmount?>;
        var google_conversion_currency = "TRY";
        var google_remarketing_only = false;
        /* ]]> */
    </script>
    <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js"></script>
    <noscript>
        <div style="display:inline;">
            <img height="1" width="1" style="border-style:none;" alt=""
                src="//www.googleadservices.com/pagead/conversion/<?= \TeknoETicaret\Config\Settings::get('adwords.remarketing.conversionid') ?>/?label=BMP4CNK31VwQjoag-AM&amp;guid=ON&amp;script=0&amp;value=<? echo $orderTotalAmount ?>&amp;conversion_currency=TRY"/>
        </div>
    </noscript>
    <? /* END Google Adwords */ ?>
    <? /* BEGIN - Adwords Remarketing */ ?>
    <script type="text/javascript">
        var google_tag_params = {
            ecomm_prodid: ["<?=implode('","', $productIds)?>"],
            ecomm_pagetype: "purchase",
            ecomm_totalvalue: <?=$orderTotalAmount?>
        };
    </script>
    <script type="text/javascript">
        /* <![CDATA[ */
        var google_conversion_id = <?= \TeknoETicaret\Config\Settings::get('adwords.remarketing.conversionid') ?>;
        var google_custom_params = window.google_tag_params;
        var google_remarketing_only = true;
        var google_conversion_format = 3;
        /* ]]> */
    </script>
    <script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js"></script>
    <noscript>
        <div style="display:inline;">
            <img height="1" width="1" style="border-style:none;" alt=""
                src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/<?= \TeknoETicaret\Config\Settings::get('adwords.remarketing.conversionid') ?>/?value=0&amp;guid=ON&amp;script=0"/>
        </div>
    </noscript>
    <? /* END - Adwords Remarketing */ ?>
<? } ?>
