<?
/**
 * @var member_delivery_address_model $deliveryAddress
 * @var array $cityList
 * @var array $townList
 * @var array $districtList
 */
$editMode = $deliveryAddress->has();
?>
<div class="modal fade" id="addressModal" tabindex="-1" role="dialog" aria-labelledby="addressesLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="addressesLabel"><?= ($editMode ? "Teslimat Adresini Düzenle" : "Yeni Teslimat Adresi Ekle") ?></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form" id="addressform" action="/account/saveDeliveryAddress" onsubmit="return false;" method="post">
                    <div class="form-group">
                        <label for="address_title" class="col-xs-4 control-label">Adres Başlığı</label>
                        <div class="col-xs-6">
                            <input type="text" class="form-control" name="address_title" id="address_title" maxlength="48" value="<?= $deliveryAddress->address_title ?>"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="recipient_name" class="col-xs-4 control-label">Alıcı Adı</label>
                        <div class="col-xs-6">
                            <input type="text" class="form-control" name="recipient_name" id="recipient_name" maxlength="128" value="<?= $deliveryAddress->recipient_name ?>"
                                placeholder="Teslim Alacak Kişi"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="city_id" class="col-xs-4 control-label">Şehir</label>
                        <div class="col-xs-6">
                            <?= form::select("city_id", $cityList, $deliveryAddress->city_id, array(
                                'onchange' => "OASIS.fetchLinkedField('/ajax/towns/',this.value,'#town_id')",
                                'class' => 'form-control',
                            )) ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="town_id" class="col-xs-4 control-label">İlçe</label>
                        <div class="col-xs-6">
                            <?=
                            form::select("town_id", $townList, $deliveryAddress->town_id, array(
                                'id' => 'town_id',
                                'onchange' => "OASIS.fetchLinkedField('/ajax/districts/',this.value,'#district_id')",
                                'class' => 'form-control',
                            )) ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="district_id" class="col-xs-4 control-label">Semt</label>
                        <div class="col-xs-6">
                            <?= form::select("district_id", $districtList, $deliveryAddress->district_id, array('id' => "district_id", 'class' => 'form-control')) ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="addressText" class="col-xs-4 control-label">Adres</label>
                        <div class="col-xs-6">
                            <textarea class="form-control" id="addressText" name="address_text" cols="30" rows="2"><?= $deliveryAddress->address_text ?></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="postcode" class="col-xs-4 control-label">Posta Kodu</label>
                        <div class="col-xs-6">
                            <input type="text" class="form-control" name="postcode" id="postcode" maxlength="5" value="<?= $deliveryAddress->postcode ?>"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="phone_number" class="col-xs-4 control-label">Telefon</label>
                        <div class="col-xs-6">
                            <input type="tel" class="form-control" id="phone_number" name="phone_number" maxlength="20" value="<?= $deliveryAddress->phone_number ?>"
                                placeholder="05321234567"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-offset-4 col-xs-8">
                            <button type="submit" class="btn btn-warning"><?= ($editMode ? "Adresi Güncelle" : "Adres Oluştur") ?></button>
                        </div>
                    </div>
                    <input type="hidden" name="delivery_address_id" value="<?= ($editMode ? $deliveryAddress->delivery_address_id : 0) ?>"/>
                    <input type="hidden" name="form" value="member-delivery-address-form"/>
                    <input type="hidden" name="redirect" value="<?= (isset($redirect) ? $redirect : '') ?>"/>
                </form>
                <script type="text/javascript">
                    $(function () {
                        $("#addressform").validate({
                            rules: {
                                recipient_name: {required: true, minlength: 5, maxlength: 50},
                                city_id: {required: true, min: 1},
                                town_id: {required: true, min: 1},
                                address_text: {required: true},
                                phone_number: {minlength: 10, digits: true, required: true}
                            }, messages: {
                                recipient_name: "Alıcı Adı 5 Karakterden Kısa Olamaz",
                                city_id: "Lütfen Şehir Seçiniz",
                                town_id: "Lütfen İlçe Seçiniz",
                                address_text: "Adresinizi giriniz"
                            },
                            submitHandler: function () {
                                var $form = $('#addressform');
                                $.post($form.attr('action'), $form.serialize(), function (response) {
                                    if (typeof response == "string") {
                                        response = $.parseJSON(response);
                                    }
                                    if (response.status == "OK") {
                                        window.location.reload();
                                    } else {
                                        alert(response.msg);
                                    }
                                });
                            }
                        });
                    });
                </script>
            </div>
        </div>
    </div>
</div>
