<?
/**
 * @var member_invoice_info_model $invoiceInfo
 * @var array $cityList
 * @var array $townList
 * @var array $districtList
 */
$editMode = $invoiceInfo->has();
?>
<div class="modal fade" id="addressModal" tabindex="-1" role="dialog" aria-labelledby="addressesLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="addressesLabel"><?= ($editMode ? "Fatura Bilgisini Düzenle" : "Yeni Fatura Bilgisi Ekle") ?></h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal" role="form" id="addressform" action="/account/saveInvoiceInfo" onsubmit="return false;" method="post">
                    <div class="form-group">
                        <label for="address_title" class="col-xs-4 control-label">Adres Adı</label>
                        <div class="col-xs-6">
                            <input type="text" class="form-control" name="address_title" id="address_title" maxlength="48" value="<?= $invoiceInfo->address_title ?>"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="city_id" class="col-xs-4 control-label">Şehir</label>
                        <div class="col-xs-6">
                            <?= form::select("city_id", $cityList, $invoiceInfo->city_id, array(
                                'onchange' => "OASIS.fetchLinkedField('/ajax/towns/',this.value,'#town_id')",
                                'class' => 'form-control',
                            )) ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="town_id" class="col-xs-4 control-label">İlçe</label>
                        <div class="col-xs-6">
                            <?=
                            form::select("town_id", $townList, $invoiceInfo->town_id, array(
                                'id' => 'town_id',
                                'onchange' => "OASIS.fetchLinkedField('/ajax/districts/',this.value,'#district_id')",
                                'class' => 'form-control',
                            )) ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="district_id" class="col-xs-4 control-label">Semt</label>
                        <div class="col-xs-6">
                            <?= form::select("district_id", $districtList, $invoiceInfo->district_id, array('id' => "district_id", 'class' => 'form-control')) ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="addressText" class="col-xs-4 control-label">Adres</label>
                        <div class="col-xs-6">
                            <textarea class="form-control" id="addressText" name="address_text" cols="30" rows="2"><?= $invoiceInfo->address_text ?></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="postcode" class="col-xs-4 control-label">Posta Kodu</label>
                        <div class="col-xs-6">
                            <input type="text" class="form-control" name="postcode" id="postcode" maxlength="5" value="<?= $invoiceInfo->postcode ?>"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="phone_number" class="col-xs-4 control-label">Telefon</label>
                        <div class="col-xs-6">
                            <input type="tel" class="form-control" id="phone_number" name="phone_number" maxlength="20" value="<?= $invoiceInfo->phone_number ?>"
                                placeholder="05321234567"/>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="addressType" class="col-xs-4 control-label"></label>
                        <div class="col-xs-6">
                            <?= form::radio("address_type", member_invoice_info_model::$addressTypes, $invoiceInfo->address_type,
                                array('onclick' => "changeAddressType(this.value)")) ?>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="tax_payer" class="col-xs-4 control-label" id="tax_payer_label">Firma Adı</label>
                        <div class="col-xs-6">
                            <input type="text" class="form-control" id="tax_payer" name="tax_payer" maxlength="256" value="<?= $invoiceInfo->tax_payer ?>"/>
                        </div>
                    </div>
                    <div class="form-group corporate">
                        <label for="tax_department" class="col-xs-4 control-label">Vergi Dairesi</label>
                        <div class="col-xs-6">
                            <input type="text" class="form-control" id="tax_department" name="tax_department" maxlength="64" value="<?= $invoiceInfo->tax_department ?>"/>
                        </div>
                    </div>
                    <div class="form-group corporate">
                        <label for="tax_no" class="col-xs-4 control-label">Vergi Numarası</label>
                        <div class="col-xs-6">
                            <input type="text" class="form-control" id="tax_no" name="tax_no" maxlength="10" value="<?= $invoiceInfo->tax_no ?>"/>
                        </div>
                    </div>
                    <div class="form-group corporate">
                        <div class="col-xs-offset-4 col-xs-8">
                            <div class="checkbox">
                                <label> <input type="checkbox" name="is_efatura_user" <?= (!$invoiceInfo->is_efatura_user ? 'checked="checked"' : "") ?>>
                                    E-Fatura mükellefiyim.</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-group personal">
                        <label for="tc_kimlik" class="col-xs-4 control-label">T.C. Kimlik No</label>
                        <div class="col-xs-6">
                            <input type="text" class="form-control" id="tc_kimlik" name="tc_identification_no" maxlength="11" value="<?= $invoiceInfo->tc_identification_no ?>">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-xs-offset-4 col-xs-8">
                            <button type="submit" class="btn btn-warning"><?= ($editMode ? "Bilgileri Güncelle" : "Fatura Bilgisini Kaydet") ?></button>
                        </div>
                    </div>
                    <input type="hidden" name="invoice_info_id" value="<?= ($editMode ? $invoiceInfo->invoice_info_id : 0) ?>"/>
                    <input type="hidden" name="form" value="member-invoice-info-form"/>
                    <input type="hidden" name="redirect" value="<?= (isset($redirect) ? $redirect : '') ?>"/>
                </form>
                <script type="text/javascript">
                    function changeAddressType(adtype) {
                        if (adtype == "Personal") {
                            $(".corporate").hide();
                            $(".personal").show();
                            $("#tax_payer_label").html("Ad Soyad");
                        } else {
                            $(".corporate").show();
                            $(".personal").hide();
                            $("#tax_payer_label").html("Firma Adı");
                        }
                    }
                    $(function () {
                        changeAddressType($("input[name=address_type]:checked").val());
                        $("#addressform").validate({
                            rules: {
                                tax_payer: {required: true, minlength: 5, maxlength: 256},
                                city_id: {required: true, min: 1},
                                town_id: {required: true, min: 1},
                                address_text: {required: true},
                                tax_department: {required: true},
                                tax_no: {minlength: 10, digits: true, required: true},
                                tc_identification_no: {minlength: 11, digits: true, required: true},
                                phone_number: {minlength: 10, digits: true, required: true}
                            }, messages: {
                                tax_payer: "Mükellef adınız 5 karakterden kısa olamaz",
                                city_id: "Lütfen şehir seçiniz",
                                town_id: "Lütfen ilçe seçiniz",
                                address_text: "Adresinizi giriniz",
                                tax_department: "Vergi Dairesi boş olamaz",
                                tax_no: "Vergi Numarası 10 basamaklı numara olmalıdır.",
                                tc_identification_no: "TC Kimlik Numaranız 11 basamaklı olmalıdır"
                            },
                            submitHandler: function () {
                                var $form = $('#addressform');
                                $.post($form.attr('action'), $form.serialize(), function (response) {
                                    if (typeof response == "string") {
                                        response = $.parseJSON(response);
                                    }
                                    if (response.status == "OK") {
                                        window.location.reload();
                                    } else {
                                        alert(response.msg);
                                    }
                                });
                            }
                        });
                    });
                </script>
            </div>
        </div>
    </div>
</div>
