<?
/**
 * @var member_invoice_info_model[] $invoiceInfos
 */
?>
<div class="alert alert-info mb">
    Bu bölümde yeni fatura bilgisi oluşturabilir, mevcut fatura bilgilerinizi düzenleyebilir ya da silebilirsiniz.
    Yapacağınız değişiklikler, daha önce vermiş olduğunuz siparişleri etkilemez.
</div>
<div class="row">
    <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="address-item-new box">
            <a class="b" data-toggle="modal" data-target="#addresses" onclick="manageInvoiceInfo('0')">
                <i class="glyphicon glyphicon-plus" style="font-size:30px"></i><br> Yeni Fatura Bilgisi Ekle
            </a>
        </div>
    </div>
    <? if ($invoiceInfos) { ?>
        <? foreach ($invoiceInfos as $invoiceInfo) { ?>
            <div id="invoiceInfo<?= $invoiceInfo->invoice_info_id ?>" class="col-md-4 col-sm-6 col-xs-12">
                <div class="address-item box">
                    <div class="address-item-content">
                        <?= $invoiceInfo->formatView() ?>
                        <div class="address-buttons">
                            <a class="btn btn-xs btn-warning" onclick="manageInvoiceInfo('<?= $invoiceInfo->invoice_info_id ?>')">
                                <span class="glyphicon glyphicon-pencil"></span> Düzenle</a>
                            <a class="btn btn-xs btn-danger" onclick="removeInvoiceInfo('<?= $invoiceInfo->invoice_info_id ?>')">
                                <span class="glyphicon glyphicon-remove"></span> Sil</a>
                        </div>
                    </div>
                </div>
            </div>
        <? } ?>
    <? } ?>
</div>
<script type="text/javascript">
    function manageInvoiceInfo(addressId) {
        $.get("/account/manageInvoiceInfo/" + addressId + "/?ajax=1", function (data) {
            if (typeof data == "string")
                data = $.parseJSON(data);
            $('body').append(data.Content);
            $('#addressModal').modal('toggle');
        });
    }
    function removeInvoiceInfo(addressId) {
        if (confirm('Bu kaydı silmek istediğinizden emin misiniz ?')) {
            $.get("/account/deleteInvoiceInfo/" + addressId + "/?ajax=1", function (data) {
                if (data == "OK") {
                    $("#invoiceInfo" + addressId).hide();
                } else {
                    alert(data);
                }
            });
        }
    }
</script>

