<div class="row">
    <div class="col-xs-7">
        <form class="form-horizontal" id="changepassword" action="/member/password" method="post" role="form">
            <div class="form-group">
                <label for="password" class="col-xs-4 control-label">Mevcut Parolanız</label>
                <div class="col-xs-7">
                    <input type="password" id="password" name="current_password" autocomplete="off" class="form-control"/>
                </div>
            </div>
            <div class="form-group">
                <label for="new_password" class="col-xs-4 control-label">Yeni Parolanız</label>
                <div class="col-xs-7">
                    <input type="password" name="new_password" class="form-control" id="new_password"/>
                </div>
            </div>
            <div class="form-group">
                <label for="new_password2" class="col-xs-4 control-label">Yeni Parolanız (Tekrar)</label>
                <div class="col-xs-7">
                    <input type="password" name="new_password2" class="form-control" id="new_password2"/>
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-offset-4 col-xs-7">
                    <button type="button" class="btn btn-warning" onclick="$('#changepassword').submit();">Parolamı Değiştir</button>
                </div>
            </div>
        </form>
        <script type="text/javascript">
            $(function () {
                $("#changepassword").validate({
                    rules: {
                        current_password: {required: true, minlength: 6},
                        new_password: {required: true, minlength: 6},
                        new_password2: {required: true, minlength: 6, equalTo: "#new_password"}
                    }
                });
            });
        </script>
    </div>
    <div class="col-xs-5">
        <ul>
            <li>Parolanızı değiştirmek için öncelikle mevcut parolanızı girmeniz gerekmektedir.</li>
            <li>Eğer mevcut parolanızı hatırlamıyorsanız giriş ekranlarımızdaki "Parolamı Unuttum" bağlantısına tıklayarak parola değiştirmek için gerekli işlemleri
                başlatabilirsiniz.
            </li>
            <li>Yeni parolanızın en az 6 karakterden oluşması gerekmektedir.</li>
            <li>Bilgilerinizin güvenliği için kolay tahmin edilebilir parolalar kullanmaktan kaçının.</li>
        </ul>
    </div>
</div>
