<?
/**
 * @var \advertisement_model[] $links
 */
?>
<? if (count($links)) { ?>
    <ul>
        <? foreach ($links as $key => $link) { ?>
            <? if (!empty($link->adv_target)) { ?>
                <li><a href="<?= $link->adv_target ?>"><?= $link->adv_text ?></a></li>
            <? } else { ?>
                <li><a><?= $link->adv_text ?></a></li>
            <? } ?>
        <? } ?>
    </ul>
<? } ?>
