<?
/**
 * @var string $content
 */
?>
<table width="650" class="deviceWidth spaced" border="0" cellpadding="0" cellspacing="0" align="center"
    style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;margin-bottom: 20px !important;">
    <tr>
        <td valign="top" class="padded" style="border-collapse: collapse;padding: 0 20px 0 20px;">
            <p style="margin: 0;font-size: 14px;line-height: 1.5em;">
                <?= $content ?>
            </p>
        </td>
    </tr>
</table>
