<? if ($response['Status'] == "OK") { ?>
    <div id="CartNoticeDialog">
        <div class="cartMessageTitle"><?= isset($response['Message']) ? $response['Message'] : 'Seçtiğiniz Ürün Sepete Eklendi!' ?></div>
        <div class="cartMessageDetails">
            Sepetinizde <strong id="cartNoticePrices"><?= $response['cartTotalPrice'] ?></strong><span>TL</span> değerinde
            <strong id="cartNoticeTotal"><?= $response['cartProductCount'] ?> ürün</strong> var.
        </div>
        <? if (isset($products) && count($products)) { ?>
            <!-- +++ cart message products -->
            <div class="cartMessageOtherProducts clear c">
                <div class="userBuy">Bu Ürünü Alanlar Bunları da Aldı!</div>
                <div style="border: 1px solid #f1f1f1; border-radius: 5px;" class="clear"><?
                    foreach ($products as $product) {
                        $product['name'] = str_replace("+", "", $product['name']);
                        $price = explode(".", number_format($product['price'], 2));
                        ?>
                        <div class="products">
                            <div>
                                <a href="<?= $product['link'] ?>"><img src="<?= $product['image'] ?>" width="129"/></a>
                            </div>
                            <div class="productsTitle">
                                <a href="<?= $product['link'] ?>"><?= mb_substr($product['name'], 0, 55) ?></a>
                            </div>
                            <div class="productsPrice"><?= $price[0] ?><span>,<?= $price[1] ?> <strong>TL</strong></span>
                            </div>
                        </div>
                    <? } ?>
                </div>
                <!-- --- cart message products -->
            </div>
        <? } ?>
        <div class="cartMessageButtons clear">
            <div class="AlisveriseDevamEt fl">
                <a href="javascript:void(0)" onclick="$('#CartNoticeDialogWindow').dialog('close');window.location.reload();">Alisverişe Devam Et</a>
            </div>
            <div class="sepeteGit fr">
                <a href="/cart">Sepete Git</a>
            </div>
        </div>
    </div>
<? } else { ?>
    <div class="modal fade" id="cart-message" tabindex="-1" role="dialog" aria-labelledby="cart-message-label" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title text-danger" id="cart-message-label">Seçtiğiniz Ürün Sepetinize Eklenemedi!</h4>
                </div>
                <div class="modal-body clearfix" style="font-size:16px;"><?= $response['Message'] ?></div>
            </div>
        </div>
    </div>
<? } ?>
