<?
/**
 * @var array $families
 * @var float $price
 * @var int   $maxInstallment
 */
?>
<div id="fullInstallmentTable" class="row mt">
    <? foreach ($families as $cardFamilyData) { ?>
        <div class="col-xs-3">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th class="CardFamily CardFamily-<?= $cardFamilyData['card_family_slug'] ?>" colspan="3"><img src="<?= $cardFamilyData['card_family_logo'] ?>"
                            alt="<?= $cardFamilyData['card_family_name'] ?>"/></th>
                </tr>
                <tr>
                    <th>Taksit</th>
                    <th class="text-right">Aylık</th>
                    <th class="text-right">Toplam</th>
                </tr>
                </thead>
                <tbody>
                <? for ($option = 2; $option <= $maxInstallment; $option++) { ?>
                    <tr>
                        <? if (isset($cardFamilyData['installments'][$option])) { ?>
                            <td><?= $cardFamilyData['installments'][$option]['text'] ?></td>
                            <td class="text-right"><?= number_format($cardFamilyData['installments'][$option]['installmentPrice'], 2) ?></td>
                            <td class="text-right <?= number_format($cardFamilyData['installments'][$option]['installment_total'], 2) == number_format($price, 2) ? 'b' : '' ?>">
                                <?= number_format($cardFamilyData['installments'][$option]['installment_total'], 2) ?>
                            </td>
                        <? } ?>
                    </tr>
                <? } ?>
                </tbody>
            </table>
        </div>
    <? } ?>
</div>
