<?
/**
 * @var ob_order $order
 * @var ob_order_package[] $orderPackages
 * @var order_products_model[] $unPackagedProducts
 * @var order_addresses_model $invoiceAddress
 * @var order_addresses_model $deliveryAddress
 */
?>
<div class="clearfix">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Sipariş Numarası</th>
            <th>Sipariş Tarihi</th>
            <th class="text-right">Sipariş Tutarı</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td class="orderDetailGeneral"><?= $order->order_code ?></td>
            <td class="orderDetailGeneral"><?= icms::format_datetime($order->order_time) ?></td>
            <td class="orderDetailGeneral text-right"><?= icms::format_money($order->sale_total) ?></td>
        </tr>
        </tbody>
    </table>
</div>
<? if ($orderPackages) {
    $i = 0;
    foreach ($orderPackages as $package) {
        $i++;
        $shippings = $package->shippings();
        ?>
        <div class="well">
            <div class="clearfix oneOrderView">
                <h2>
                    <?= $i ?>. GÖNDERİNİZ - <?= $package->package_code ?>
                    <div class="fr prLabelArea ">
                        <span class="text-right prLabel"><?= $order->order_status == ob_order::ORDER_STATUS_REVIEW ? "Onay Bekliyor" : order::show_status($package->package_status,
                                0, 0, true, true, true) ?></span>
                    </div>
                </h2>
                <div class="row">
                    <div class="col-xs-12">
                        <? if (!count($shippings)) { ?>
                            <div clasS="row r">
                                <div class="col-xs-12">
                                    Tahmini Gönderim Tarihi: <?= icms::format_date($package->estimated_shipping_date) ?>
                                </div>
                            </div>
                        <? } ?>
                        <table class="table table-striped oneOrder">
                            <thead>
                            <tr>
                                <th class="col-xs-1">Resim</th>
                                <th class="col-xs-8">Ürün</th>
                                <th class="col-xs-1 c">Adet</th>
                                <th class="col-xs-2 r">Tutar</th>
                            </tr>
                            </thead>
                            <tbody>
                            <?
                            $totalSale = 0;
                            foreach ($package->orderProducts(true) as $orderProduct) {
                                $product = $orderProduct->product();
                                $totalSale += $orderProduct->order_sale * $orderProduct->quantity;
                                ?>
                                <tr>
                                    <td class="img">
                                        <img src="<?= $product->getPhoto() ?>" height="40"/>
                                    </td>
                                    <td class="link">
                                        <a href="<?= link::toProduct($product) ?>" target="_blank">
                                            <?= $product->full_name ?>
                                        </a>
                                    </td>
                                    <td class="number c"><?= $orderProduct->quantity ?></td>
                                    <td class="price text-right"><?= icms::format_money($orderProduct->order_sale * $orderProduct->quantity) ?></td>
                                </tr>
                            <? } ?>
                            <? if ($package->sale_shipping > 0) {
                                $totalSale += $package->sale_shipping;
                                ?>
                                <tr>
                                    <td colspan="3" class="r b col-xs-10">Kargo Ücreti:</td>
                                    <td class="r b col-xs-2"><?= icms::format_money($package->sale_shipping) ?></td>
                                </tr>
                            <? } ?>
                            <tr>
                                <td colspan="3" class="r b col-xs-10">Gönderi Toplamı:</td>
                                <td class="r b col-xs-2"><?= icms::format_money($totalSale) ?></td>
                            </tr>
                            </tbody>
                        </table>
                        <? if (count($shippings)) { ?>
                            <table class="table table-striped margin0-0">
                                <thead>
                                <tr>
                                    <th>Firma</th>
                                    <th>Takip Kodu</th>
                                    <th>Gönderim Zamanı</th>
                                    <th>Kargo Durumu</th>
                                </tr>
                                </thead>
                                <tbody>
                                <? foreach ($shippings as $shipping) { ?>
                                    <tr>
                                        <td><?= $shipping->shippingCompany()->company_name ?></td>
                                        <td><?= $shipping->company_track_code ?></td>
                                        <td><?= icms::format_datetime($shipping->shipping_time) ?></td>
                                        <td><?= $shipping->shippingStatusText() ?></td>
                                    </tr>
                                <? } ?>
                                </tbody>
                            </table>
                        <? } ?>
                    </div>
                </div>
            </div>
        </div>
    <? } ?>
<? } ?>

<? if ($unPackagedProducts) { ?>
    <div class="well">
        <div class="clearfix oneOrderView">
            <h2>BEKLEYEN ÜRÜNLER</h2>
            <div class="row">
                <div class="col-xs-12">
                    <table class="table table-hover oneOrder">
                        <thead>
                        <tr>
                            <th></th>
                            <th>Ürün</th>
                            <th class="text-right">Adet</th>
                            <th class="text-right">Tutar</th>
                        </tr>
                        </thead>
                        <tbody>
                        <?
                        $totalSale = 0;
                        foreach ($unPackagedProducts as $orderProduct) {
                            $product = $orderProduct->product();
                            $totalSale += $orderProduct->order_sale * $orderProduct->quantity;
                            ?>
                            <tr>
                                <td class="img">
                                    <img src="<?= $product->getPhoto() ?>" height="40"/>
                                </td>
                                <td class="link">
                                    <a href="<?= link::toProduct($product) ?>" target="_blank">
                                        <?= $product->full_name ?>
                                    </a>
                                </td>
                                <td class="number text-right"><?= $orderProduct->quantity ?></td>
                                <td class="price text-right"><?= icms::format_money($orderProduct->order_sale * $orderProduct->quantity) ?></td>
                            </tr>
                        <? } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
<? } ?>
<div class="mt clearfix">
    <h2>ADRES BİLGİLERİ</h2>
    <table class="mt table table-striped addressArea">
        <thead>
        <tr>
            <th>Teslimat Adresi</th>
            <th>Fatura Bilgileri</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td class="address">
                <? if ($deliveryAddress) { ?>
                    <? if ($invoiceAddress->address_type == order_addresses_model::ADDRESS_TYPE_COMPANY) { ?>
                        <strong><?= $deliveryAddress->company_name ?></strong> Alıcı:
                    <? } ?>
                    <strong><?= $deliveryAddress->owner_name ?></strong><br/>
                    <?= $deliveryAddress->address_text ?> <?= $deliveryAddress->district()->district_name ?> / <?= $deliveryAddress->town()->town_name ?> / <?= $deliveryAddress->city()->city_name ?>
                    <br/> Telefon: <?= $deliveryAddress->telephone ?>
                <? } else { ?>
                    Adres bilgilerinde hata var lütfen müşteri hizmetlerine ulaşarak bilgileri güncelletiniz.
                <? } ?>
            </td>
            <td class="address">
                <? if ($invoiceAddress) { ?>
                    <? if ($invoiceAddress->address_type == order_addresses_model::ADDRESS_TYPE_COMPANY) { ?>
                        <strong><?= $invoiceAddress->company_name ?></strong><br/>
                        <?= $invoiceAddress->address_text ?> <?= $invoiceAddress->district()->district_name ?> / <?= $invoiceAddress->town()->town_name ?> / <?= $invoiceAddress->city()->city_name ?>
                        <br/> Telefon: <?= $invoiceAddress->telephone ?>
                        <br/> <?= $invoiceAddress->tax_department ?> V.D., No: <?= $invoiceAddress->tax_no ?>
                    <? } else { ?>
                        <strong><?= $invoiceAddress->owner_name ?></strong><br/>
                        <?= $invoiceAddress->address_text ?> <?= $invoiceAddress->district()->district_name ?> / <?= $invoiceAddress->town()->town_name ?> / <?= $invoiceAddress->city()->city_name ?>
                        <br/> Telefon: <?= $invoiceAddress->telephone ?> | T.C. No: <?= $invoiceAddress->tc_kimlik ?>
                    <? } ?>
                <? } else { ?>
                    Fatura bilgilerinde hata var lütfen müşteri hizmetlerine ulaşarak bilgileri güncelletiniz.
                <? } ?>
            </td>
        </tr>
        </tbody>
    </table>
</div>
<? if (false) { ?>
    <div class="clearfix">
        <h2>ÖDEME ŞEKLİ</h2>
        <table class="mt table table-striped addressArea">
            <thead>
            <tr>
                <th>Kart Adı</th>
                <th>Kart No</th>
                <th>Taksit</th>
                <th>Durum</th>
                <th class="text-right">Tutar</th>
            </tr>
            </thead>
            <tbody>
            <?
            $totalSale = 0;
            foreach ($payments as $payment) {
                $totalSale += $payment['amount'];
                ?>
                <tr>
                    <td><?= $payment['card_name'] ?></td>
                    <td><?= $payment['ccno'] ?></td>
                    <td><?= (!empty($payment['installment_text']) ? $payment['installment_text'] : "Yok") ?></td>
                    <td><?= ($payment['charge_status'] != "Onaylandı" ? '<span class="text-danger b" title="' . $payment['error_msg'] . ' (' . $payment['error_code'] . ')">' . $payment['charge_status'] . '</span>' : '<span class="text-success b" >Ödeme Alındı</span>') ?></td>
                    <td class="text-right b"><?= icms::format_money($payment['amount']) ?></td>
                </tr>
                <?
                if (isset($refunds[$payment['charge_id']])) {
                    foreach ($refunds[$payment['charge_id']] as $refund) {
                        if ($refund['refund_status'] == 1) {
                            $totalSale -= $refund['amount'];
                        } ?>
                        <tr>
                            <td colspan="3" class="text-right"><?= $refund['transaction_id'] ?></td>
                            <td><?= $refund['refund_status'] == 0 ? '<span class="text-primary">İade Bekliyor</span>' : "<span class='text-danger'>İade Yapıldı</span>" ?></td>
                            <td class="text-right b">
                                <?= icms::format_money($refund['amount']) ?>
                            </td>
                        </tr>
                        <?
                    }
                }
            } ?>
            </tbody>
            <tfoot>
            <tr>
                <td colspan="5" class="text-right">
                    <strong>Toplam: <?= icms::format_money($totalSale) ?></strong>
                </td>
            </tr>
            </tfoot>
        </table>
    </div>
<? } ?>
