<?
/**
 * @var string $title
 * @var \product_item[] $products
 * @var \product_item[] $row
 */
?>
<div class="widget homeProductList mb">
    <h4><?= $title ?></h4>
    <? while (count($products) > 0) { ?>
        <? $row = array_splice($products, 0, 4) ?>
        <div class="row">
            <? foreach ($row as $key => $product) { ?>
                <div class="col-xs-3">
                    <?= $product->generate() ?>
                </div>
            <? } ?>
        </div>
    <? } ?>
</div>
