<?
/**
 * @var \advertisement_model[] $banners
 * @var \advertisement_zone_model $zone
 * @var bool $lazyLoad
 * @var string $id
 */
?>
<div id="<?= $id ?>" class="carousel slide" data-ride="carousel" style="height: <?= $zone->zone_height ?>px; overflow: hidden">
    <ol class="carousel-indicators">
        <? foreach ($banners as $key => $banner) { ?>
            <li data-target="#<?= $id ?>" data-slide-to="<?= $key ?>" <?= ($key == 0 ? 'class="active"' : '') ?>><? if ($zone->has_thumb_image == 1) { ?><? } ?></li>
        <? } ?>
    </ol>
    <div class="carousel-inner" role="listbox">
        <? foreach ($banners as $key => $banner) { ?>
            <div class="item <?= ($key == 0 ? 'active' : '') ?>">
                <?= image::getBannerHtml($banner) ?>
            </div>
        <? } ?>
    </div>
    <a class="left carousel-control" href="#<?= $id ?>" role="button" data-slide="prev"> <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> </a>
    <a class="right carousel-control" href="#<?= $id ?>" role="button" data-slide="next"> <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> </a>
</div>
<? if ($lazyLoad) { ?>
    <script>
        $(function () {
            $('#<?=$id?>').on('slide.bs.carousel', function () {
                var $nextImage = $('.active.item', this).next('.item').find('img');
                $nextImage.trigger("sporty");
            }).find("img.lazy").lazyload({effect: "fadeIn", event: "sporty"});
        });
    </script>
<? } ?>
