<?php
/**
 * @var string $CaymaHakki
 * @var string $OnBilgilendirmeFormu
 * @var string $MesafeliSatisSozlesmesi
 */
?>
<h3>Cayma Hakkı</h3>
<div class="agreementBox">
    <div style="font-size: 12pt !important; font-family: Helvetica, Arial, sans-serif; font-weight: bold">
        <?= $CaymaHakki ?>
    </div>
</div>
<h3 id="InfoForm">Ön Bilgilendirme Formu</h3>
<div class="agreementBox">
    <div style="font-size: 12pt !important;; font-family: Helvetica, Arial, sans-serif; font-weight: bold">
        <?= $OnBilgilendirmeFormu ?>
    </div>
</div>
<h3 id="PurchaseAgreement">Mesafeli Satış Sözleşmesi</h3>
<div class="agreementBox">
    <div style="font-size: 12pt !important;; font-family: Helvetica, Arial, sans-serif; font-weight: bold">
        <?= $MesafeliSatisSozlesmesi ?>
    </div>
</div>
