<?
/**
 * @var \TeknoETicaret\Shopping\Cart\Cart              $cart
 * @var \TeknoETicaret\Shopping\Object\Checkout        $checkout
 * @var \TeknoETicaret\Shopping\Object\DeliveryAddress $deliveryAddress
 * @var \TeknoETicaret\Shopping\Object\InvoiceInfo     $invoiceInfo
 * @var string|null                                    $buttonClass
 * @var string|null                                    $buttonTitle
 * @var string                                         $paymentMethodName
 * @var bool                                           $showAggrements
 * @var bool                                           $addressesSet
 * @var bool                                           $changeButtons
 */
?>
<div class="orderSummaryDetails mb">
    <h2 class="cartColor">SİPARİŞ ÖZETİNİZ</h2>
    <? if ($cart->getShippingCost() < $cart->getBaseShippingCost()) { ?>
        <div class="orderArea pb5 mb5 row">
            <div class="col-xs-1"><i class="glyphicon glyphicon-ok-circle"></i></div>
            <div class="col-xs-11">
                <strong><?= ($cart->getShippingCost() == 0 ? 'Ücretsiz' : 'İndirimli') ?> kargo</strong> fırsatını yakaladınız.
            </div>
        </div>
    <? } ?>
    <div class="orderArea pb5 mb5 clearfix">
        <div class="col-xs-6">Sepet Toplamı :</div>
        <div class="col-xs-6 text-right priceStrong"><?= icms::format_money($cart->getTotalProductPrice()) ?></div>
    </div>
    <div class="orderArea pb5 mb5 clearfix shippingFee">
        <div class="col-xs-6">Kargo Ücreti :</div>
        <div class="col-xs-6 text-right priceStrong">
            <? if ($cart->getShippingCost() < $cart->getBaseShippingCost()) { ?>
                <del><?= icms::format_money($cart->getBaseShippingCost()) ?></del>
            <? } ?>
            <?= ($cart->getShippingCost() > 0 ? icms::format_money($cart->getShippingCost()) : 'Ücretsiz') ?>
        </div>
    </div>
    <? if ($checkout->shoppingCheckId > 0 && $cart->getCheckCouponDiscountAmount() > 0) { ?>
        <div class="orderArea pb5 mb5 clearfix">
            <div class="col-xs-6">Alışveriş Çeki :</div>
            <div class="col-xs-6 text-right priceStrong">- <?= icms::format_money($cart->getCheckCouponDiscountAmount()) ?></div>
        </div>
    <? } ?>
    <? if ($checkout->couponCodeId > 0 && $cart->getCheckCouponDiscountAmount() > 0) { ?>
        <div class="orderArea pb5 mb5 clearfix">
            <div class="col-xs-6">Kupon Kodu :</div>
            <div class="col-xs-6 text-right priceStrong"> - <?= icms::format_money($cart->getCheckCouponDiscountAmount()) ?></div>
        </div>
    <? } ?>
    <? if ($cart->hasPaymentMethodEffect()) { ?>
        <? view::add_message("hasPaymentMethodEffect")?>
        <? if ($checkout->paymentMethod == payment_method_model::METHOD_KEY_CREDITCARD && $cart->getInstallmentCommission() > 0) { ?>
            <div class="orderArea pb5 mb5 clearfix">
                <div class="col-xs-6">Vade Farkı :</div>
                <div class="col-xs-6 text-right priceStrong"><?= icms::format_money($cart->getInstallmentCommission()) ?></div>
            </div>
        <? } ?>
        <? if ($cart->getPaymentMethodDiscount() > 0) { ?>
            <? view::add_message("getPaymentMethodDiscount() > 0")?>
            <div class="orderArea pb5 mb5 clearfix">
                <div class="col-xs-8"><?= $paymentMethodName ?> İndirimi :</div>
                <div class="col-xs-4 text-right priceStrong">- <?= icms::format_money($cart->getPaymentMethodDiscount()) ?></div>
            </div>
        <? } else {?>
            <? view::add_message("getPaymentMethodDiscount() = ". $cart->getPaymentMethodDiscount())?>
        <? } ?>
        <? if ($checkout->paymentMethod == payment_method_model::METHOD_KEY_ONDELIVERY && $cart->getPaymentServiceCost() > 0) { ?>
            <div class="orderArea pb5 mb5 clearfix">
                <div class="col-xs-8">Hizmet Bedeli:</div>
                <div class="col-xs-4 text-right priceStrong"><?= icms::format_money($cart->getPaymentServiceCost()) ?></div>
            </div>
        <? } ?>
    <? } ?>
    <? if ($checkout->hasMemberBalance) { ?>
        <div class="orderArea pb5 mb5 clearfix">
            <div class="col-xs-6">Bakiye Kullanımı :</div>
            <div class="col-xs-6 text-right priceStrong">- <?= icms::format_money($cart->getMemberBalance()) ?></div>
        </div>
    <? } ?>
    <div class="orderArea pb5 mb5 clearfix text-center">
        <div class="totalPrice"><span>Ödenecek Tutar</span><br>
            <strong class="totalChargeAmount"><?= icms::format_money(max($cart->getTotalPrice() - $cart->getMemberBalance(), 0)) ?></strong>
        </div>
        <? if ($showAggrements) { ?>
            <div class="text-left">
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="AcceptInfoForm"> <a href="#InfoForm" class="b">Ön Bilgilendirme formunu</a> kabul ediyorum
                    </label>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="AcceptPurchaseAgreement"> <a href="#PurchaseAgreement" class="b">Mesafeli Satış Sözleşmesini</a> kabul ediyorum
                    </label>
                </div>
            </div>
        <? } ?>
        <div class="totalPrice">
            <a href="javascript:" type="button"
                class="<?= (!is_null($buttonClass) ? $buttonClass : 'btn btn-warning Buy noiseBg continueBtn') ?>">
                <?= (!is_null($buttonTitle) ? $buttonTitle : 'Satın Al') ?>
            </a>
        </div>
    </div>
</div>
<? if ($addressesSet) { ?>
    <div class="orderCartDetails mb">
        <h2 class="text-left m0">ADRES BİLGİLERİ
            <? if ($changeButtons) { ?>
                <a href="/checkout/delivery" style="margin-top: 3px; font-size: 9px;" class="pull-right btn btn-default btn-xs"><i class="glyphicon glyphicon-pencil"></i> DEĞİŞTİR</a>
            <? } ?>
        </h2>
        <? if ($deliveryAddress) { ?>
            <table class="table">
                <thead>
                <tr style="background-color: #f9f9f9;">
                    <th><?= (!$checkout->useSeperateInvoiceAddress ? 'Teslimat ve Fatura Adresi' : 'Teslimat Adresi') ?> </th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td class="selectedAddress"><?= $deliveryAddress->address_text . '<br>' ?>
                        <?= $deliveryAddress->district_name . " - " . $deliveryAddress->town_name . ' - ' . $deliveryAddress->city_name ?></td>
                </tr>
                </tbody>
            </table>
        <? } ?>
        <? if ($invoiceInfo && $checkout->useSeperateInvoiceAddress) { ?>
            <table class="table">
                <thead>
                <tr style="background-color: #f9f9f9;">
                    <th>Fatura Bilgileri</th>
                </tr>
                </thead>
                <tbody>
                <tr>
                    <td class="selectedAddress"><?= $invoiceInfo->address_text . '<br>' ?>
                        <?= $invoiceInfo->district_name . " - " . $invoiceInfo->town_name . ' - ' . $invoiceInfo->city_name ?></td>
                </tr>
                </tbody>
            </table>
        <? } ?>
    </div>
<? } ?>
<div class="orderCartDetails clearfix mb">
    <h2 class="text-left m0">SEPETTEKİ ÜRÜNLER
        <a href="/cart" style="margin-top: 3px; font-size: 9px;" class="pull-right btn btn-default btn-xs"><i class="glyphicon glyphicon-pencil"></i> DEĞİŞTİR</a></h2>
    <table class="table">
        <thead>
        <tr style="background-color: #f9f9f9;">
            <th>Ürün</th>
            <th class="text-right">Adet</th>
        </tr>
        </thead>
        <tbody>
        <? foreach ($cart->getProducts() as $cartProduct) {
            $product = $cartProduct->getProduct() ?>
            <tr>
                <td class="inCartPr"><?= $product->full_name ?></td>
                <td class="text-right"><?= $cartProduct->getQuantity() ?></td>
            </tr>
        <? } ?>
        </tbody>
    </table>
</div>
