<?
/**
 * @var \TeknoETicaret\Shopping\Cart\Cart $cart
 */
?>
<div id="BKMExpressPayment">
    <h2>BKM Express</h2>
    <img class="pull-right" alt="" src="/img/bank_logo/bkm-express.png">
    <p>BKM Express ile ödeme yaparken www.bkmexpress.com.tr sayfasına yönlendirileceksiniz.</p>
    <p>BKM Express sitesine üye olurken kullandığınız kullanıcı adı ve şifreniz ile uygulamaya giriş yapmanız gerekmektedir. Karşınıza gelen ödeme ekranından işlem yapmak
        istediğiniz kartı ve tercihlerinizi seçerek kolayca ödeme yapabilirsiniz. </p>
    <p>Alışverişinizi tamamladıktan sonra otomatik olarak <?= icms::site_com("a") ?> döneceksiniz.</p>
</div>
