<?
/**
 * @var \TeknoETicaret\Shopping\Cart\Cart $cart
 */
?>
<div id="BalancePayment">
    <h2>Bakiye ile Öde</h2>
    <div class="row">
        <div class="col-xs-12">
            <div class="alert alert-info" role="alert">
                <p><strong>Kullanılabilir Bakiye: <?= icms::format_money($cart->getMemberBalance()) ?></strong></p>
                <p>Hesabınızdaki bakiye ile siparişinizi tamamlayabilirsiniz.</p>
                <div class="checkbox">
                    <label> <input type="checkbox" id="useBalance"> <strong>Evet bakiyemi kullan</strong> </label>
                </div>
            </div>
        </div>
        <div class="col-xs-12">
            <form action="/checkout/balance" method="POST" id="frmBalance">
                <input type="hidden" name="act" value="complete">
            </form>
        </div>
    </div>
</div>
