<?
/**
 * @var string $slider
 * @var string $banners
 * @var array $widgets
 */
?>
<div class="home">
    <? if (isset($slider)) { ?>
        <div class="row mb">
            <div class="col-xs-9 col-xs-offset-3">
                <?= $slider ?>
            </div>
        </div>
    <? } ?>
    <!-- menü ve slider sonu -->
    <? if (isset($banners)) { ?>
        <?= $banners ?>
    <? } ?>
    <!-- 2 banner sonu -->
    <? if (isset($widgets)) { ?>
        <?= implode("", $widgets) ?>
    <? } ?>
</div>
