<?
/**
 * @var payment_wire_transfer_model $wireTransfer
 * @var ob_order $order
 * @var string $wireTransferNotes
 */
?>
<div align="center" class="col-xs-8 col-xs-offset-2 checkoutStep">
    <div class="checkoutStep3"></div>
</div>
<div class="row">
    <div class="col-xs-8">
        <div class="checkoutContent mb">
            <h2 class="basketColor">SİPARİŞİNİZ TAMAMLANDI</h2>
            <div class="orderBasketDetails orderCompleteHeight clearfix mb">
                Sayın <?= mb_strtoupper(session::get("fullName")) ?>,
                <p class="completeThanks">Siparişiniz başarıyla tamamladınız.</p>
                <p class="orderNumber b" style="font-size: 14px;">Sipariş Numaranız: <?= $order->order_code ?></p>
                <p class="orderDescriptions">Siparişinizin durumunu sayfamızın sağ üstünde bulunan "Sipariş Takip" linkinden takip edebilirsiniz.</p>
                <a href="<?= app::getUrl(ACTIVE_APP, "http") . "/order/details/" . $order->order_code ?>" class="btn btn-success btn-xs">Siparişimi Görüntüle</a>
                <a href="<?= app::getUrl(ACTIVE_APP, "http") ?>" class="btn btn-default btn-xs">Anasayfaya Dön</a>
                <p class="orderWarning"><br/> <span class="b">Önemli Uyarı!</span><br/> Ürünü teslim almadan önce paket içeriğini kontrol ediniz. Hasarlı ürünlerle ilgili tutanak
                    tutturunuz.
                </p>
            </div>
            <? if ($order->payment_method == 2 && $wireTransfer) { ?>
                <? $bankAccount = new bank_accounts_model($wireTransfer->bank_account_id); ?>
                <h2 class="basketColor">Ödeme Yapacağınız Banka Bilgileri</h2>
                <div class="orderBasketDetails  clearfix mb">
                    <div class="bs-example">
                        <div class="" style="font-size: 16px;font-weight: 700"><?= $bankAccount->account_name ?></div>
                        <div class="">IBAN: <b><?= join(str_split($bankAccount->iban_number, 4), " ") ?></b></div>
                        <div class=""><?= $bankAccount->account_number ?></div>
                    </div>
                </div>
                <? if (!empty($wireTransferNotes)) { ?>
                    <div class="well" id="moneyTransferInfo">
                        <?= $wireTransferNotes ?>
                    </div>
                <? } ?>
            <? } ?>
        </div>
    </div>
    <? view::show_blocks("col-xs-4") ?>
</div>
