<?
/**
 * @var member_addresses_model[] $memberAddresses
 * @var member_addresses_model $memberAddress
 * @var ob_basket $basket
 */
?>
<div align="center" class="col-xs-8 col-xs-offset-2 checkoutStep">
    <div class="checkoutStep1">
        <ul>
            <li><a href="<?= app::getUrl(ACTIVE_APP, app::SCHEME_HTTP) ?>/basket"><span>Alışveriş Sepeti</span></a></li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-xs-8">
        <div class="checkoutContent mb">
            <h2>ADRES BİLGİLERİ</h2>
            <? if (!$memberAddresses) { ?>
                <div class="messagebox alert alert-danger">Sistemde kayıtlı adresiniz bulunmuyor</div>
            <? } ?>
            <form id="addressUpdate" method="post" action="/checkout/deliverySubmit/">
                <div class="checkoutAddressArea">
                    <div class="generalCartTitle">Teslimat Adresi</div>
                    <table class="table addressListContainer">
                        <thead>
                        <tr style="background-color: #f9f9f9;">
                            <th>Alıcı</th>
                            <th>Adres Bilgileri</th>
                            <th class="text-center">Teslimat</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <? foreach ($memberAddresses as $memberAddress) { ?>
                            <tr>
                                <td>
                                    <? if ($memberAddress->need_update) { ?>
                                        <a class="label label-danger mb5" style="display: inline-block;cursor: pointer" href="javascript:" data-toggle="modal"
                                            data-target="#addresses" onclick="address_form('<?= $memberAddress->address_id ?>')"> Güncellenme Gerekli </a>
                                        <br>
                                    <? } ?>
                                    <strong><?= $memberAddress->owner_name ?></strong></td>
                                <td>
                                    <? if ($memberAddress->address_type == member_addresses_model::ADDRESS_TYPE_COMPANY) { ?>
                                        <strong><?= $memberAddress->company_name ?></strong><br>
                                    <? } ?>
                                    <?= $memberAddress->address_text ?> <br>
                                    <?= $memberAddress->district()->district_name ?> / <?= $memberAddress->town()->town_name ?> / <?= $memberAddress->city()->city_name ?>
                                    <div class="mt5">
                                        Telefon: <?= $memberAddress->telephone ?>
                                        <span class="pull-right"><?
                                            if ($memberAddress->address_type == member_addresses_model::ADDRESS_TYPE_PERSONAL) {
                                                echo "T.C. Kimlik No: " . $memberAddress->tc_kimlik;
                                            } else {
                                                echo $memberAddress->tax_department . " V.D. No: " . $memberAddress->tax_no;
                                            }
                                            ?></span>
                                    </div>
                                </td>
                                <td class="text-center">
                                    <? $activeAddress = ($basket->invoice_address_id == $memberAddress->address_id); ?>
                                    <a href="javascript:" class="btn <?= ($activeAddress ? 'btn-success' : "btn-default") ?> btn-xs use-address"
                                        data-needupdate="<?= $memberAddress->need_update ?>" data-target="delivery-address" data-value="<?= $memberAddress->address_id ?>">
                                        <?= ($activeAddress ? 'SEÇİLİ' : "SEÇ") ?>
                                    </a>
                                </td>
                                <td>
                                    <a href="javascript:" class="btn btn-default btn-xs" data-toggle="modal" data-target="#addresses"
                                        onclick="address_form('<?= $memberAddress->address_id ?>')">
                                        <? if ($memberAddress->need_update) { ?>
                                            <i class="text-danger glyphicon glyphicon-pencil"></i>
                                        <? } else { ?>
                                            <i class="glyphicon glyphicon-pencil"></i>
                                        <? } ?>
                                    </a>
                                </td>
                            </tr>
                        <? } ?>
                        </tbody>
                        <tfoot>
                        <tr>
                            <td colspan="4" class="text-right" style="padding-right: 0">
                                <a class="btn btn-default btn-md btnAddAddress" href="javascript:" onclick="address_form(0)"><i class="glyphicon glyphicon-plus-sign"></i> Adres
                                    Ekle</a>
                            </td>
                        </tr>
                        </tfoot>
                    </table>
                </div>
                <div class="checkbox">
                    <label> <input type="checkbox" id="invoiceCheckBox"
                            name="invoice_checkbox" <?= (($basket->delivery_address_id == $basket->invoice_address_id) ? 'checked="checked"' : "") ?>>
                        <strong>Fatura bilgilerim teslimat adresimle aynı olsun.</strong> </label>
                </div>
                <div class="invAddressArea">
                    <div class="alert alert-warning">"Fatura Bilgileri" alanında yer alan bilgileriniz, faturanın kişi ya da kuruma kesileceğini belirtmektedir. Faturanız,
                        siparişinizdeki ürünlerinizle birlikte teslimat adresinize gönderilecektir.
                    </div>
                    <div class="generalCartTitle">Fatura Bilgileri</div>
                    <table class="table addressListContainer">
                        <thead>
                        <tr style="background-color: #f9f9f9;">
                            <th>Alıcı</th>
                            <th>Adres Bilgileri</th>
                            <th class="text-center">Fatura</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        <? foreach ($memberAddresses as $memberAddress) { ?>
                            <tr>
                                <td>
                                    <? if ($memberAddress->need_update) { ?>
                                        <a class="label label-danger mb5" style="display: inline-block;cursor: pointer" href="javascript:" data-toggle="modal"
                                            data-target="#addresses" onclick="address_form('<?= $memberAddress->address_id ?>')"> Güncellenme Gerekli </a>
                                        <br>
                                    <? } ?>
                                    <strong><?= $memberAddress->owner_name ?></strong>
                                </td>
                                <td>
                                    <? if ($memberAddress->address_type == member_addresses_model::ADDRESS_TYPE_COMPANY) { ?>
                                        <strong><?= $memberAddress->company_name ?></strong><br>
                                    <? } ?>
                                    <?= $memberAddress->address_text ?> <br>
                                    <?= $memberAddress->district()->district_name ?> - <?= $memberAddress->town()->town_name ?> / <?= $memberAddress->city()->city_name ?>
                                    <div class="mt5">
                                        Telefon: <?= $memberAddress->telephone ?>
                                        <span class="pull-right"><?
                                            if ($memberAddress->address_type == member_addresses_model::ADDRESS_TYPE_PERSONAL) {
                                                echo "T.C. Kimlik No: " . $memberAddress->tc_kimlik;
                                            } else {
                                                echo $memberAddress->tax_department . " V.D. No: " . $memberAddress->tax_no;
                                            }
                                            ?></span>
                                    </div>
                                </td>
                                <td class="text-center">
                                    <? $activeAddress = ($basket->invoice_address_id == $memberAddress->address_id); ?>
                                    <a href="javascript:" class="btn <?= ($activeAddress ? 'btn-success' : "btn-default") ?> btn-xs use-address"
                                        data-needupdate="<?= $memberAddress->need_update ?>" data-target="invoice-address" data-value="<?= $memberAddress->address_id ?>">
                                        <?= ($activeAddress ? 'SEÇİLİ' : "SEÇ") ?>
                                    </a>
                                </td>
                                <td>
                                    <a href="javascript:" class="btn btn-default btn-xs" data-toggle="modal" data-target="#addresses"
                                        onclick="address_form('<?= $memberAddress->address_id ?>')">
                                        <? if ($memberAddress->need_update) { ?>
                                            <i class="text-danger glyphicon glyphicon-pencil"></i>
                                        <? } else { ?>
                                            <i class="glyphicon glyphicon-pencil"></i>
                                        <? } ?>
                                    </a>
                                </td>
                            </tr>
                        <? } ?>
                        </tbody>
                        <tfoot>
                        <tr>
                            <td colspan="4" class="text-right" style="padding-right: 0">
                                <a class="btn btn-default btn-md" href="javascript:" onclick="address_form(0)"><i class="glyphicon glyphicon-plus-sign"></i> Adres Ekle</a>
                            </td>
                        </tr>
                        </tfoot>
                    </table>
                </div>
                <input type="hidden" name="form" value="checkout-cargo"/> <input type="hidden" id="cargoinput" name="cargo" value="<?= $basket->shipping_company_id ?>"/>
                <input type="hidden" id="delivery-address" name="delivery_address" value="<?= $basket->delivery_address_id ?>"/>
                <input type="hidden" id="invoice-address" name="invoice_address" value="<?= $basket->invoice_address_id ?>"/>
            </form>
        </div>
        <? if (false && session::isStaff()) { ?>
            <div class="shippingChannel mt" id="shippingchannel">
                <div class="generalCartTitle">Teslimat Şeklinizi Seçiniz</div>
                <div class="shippingChannelDescription mt">Siparişiniz <strong id="cargoinfo">Aras Kargo</strong> ile teslim edilecektir.
                </div>
                <div class="clear">
                    <ul>
                        <li class="pull-left" style="list-style-type: none;">
                            <a data-cargo="4" data-name="Aras Kargo" href="javascript:" class="img-thumbnail"><img src="/images/newbasket/shipping-channel-cargo.jpg"/></a>
                        </li>
                        <li class="pull-left" style="list-style-type: none;">
                            <a data-cargo="7" data-name="Elden Teslim" href="javascript:" class="img-thumbnail"><img src="/images/newbasket/shipping-channel-hand.jpg"/></a>
                        </li>
                    </ul>
                </div>
            </div>
            <script>
                $(function () {
                    var $shippingChannel = $('#shippingchannel');
                    var $cargolist = $shippingChannel.find('li a');
                    var selectShippingCompany = '<?= $basket->shipping_company_id ?>';
                    $cargolist.click(function () {
                        $cargolist.removeClass('selected-cargo');
                        var $this = $(this);
                        $this.addClass('selected-cargo');
                        $('#cargoinfo').html($this.data('name'));
                        $('#cargoinput').val($this.data('cargo'));
                    });
                    if (selectShippingCompany > 0) {
                        $shippingChannel.find('li a[data-cargo=' + selectShippingCompany + ']').click();
                    } else {
                        $shippingChannel.find('li a:first').click();
                    }
                }
            </script>
        <? } ?>
        <script type="text/javascript">
            function address_form(addressId) {
                $.get("/account/manageAddress/" + addressId, function (data) {
                    $('body').append(data);
                    $('.modal').modal('toggle')
                });
            }
            function differentInvoiceAddress() {
                if ($('input#invoiceCheckBox:checked').length > 0) {
                    $('.invAddressArea').hide();
                } else {
                    $('.invAddressArea').show();
                }
            }
            $(function () {
                $('.use-address').click(function () {
                    var $this = $(this);
                    var needUpdate = $this.data('needupdate');
                    if (needUpdate == 1) {
                        alert('Bu adresin güncellemesi gerekiyor.');
                        return false;
                    }
                    $('input#' + $this.data('target')).val($this.data('value'));
                    $this.parents(".addressListContainer").find('.use-address.btn-success').addClass('btn-default').removeClass('btn-success').html('SEÇ');
                    $this.addClass('btn-success').removeClass('btn-default').html('SEÇİLİ');
                });
                $('.continueBtn').click(function () {
                    if ($('input#delivery-address').val() * 1 > 0 && ( $('input#invoiceCheckBox:checked').length > 0 || $('input#invoice-address').val() * 1 > 0 )) {
                        $('form#addressUpdate').submit();
                    } else {
                        alert('Lütfen Teslimat ve Fatura Adreslerinizi Seçiniz');
                    }
                });
                $('#invoiceCheckBox').on("click", differentInvoiceAddress);
                differentInvoiceAddress();
                <? if (!$memberAddresses) { ?>
                setTimeout(function () {
                    $(".btnAddAddress").trigger("click");
                }, 500);
                <? } ?>
                $(".orderSummaryDetails a.continueBtn").on("click", function () {
                    <?
                    $products = array();
                    foreach ($basket->productData as $basketProduct) {
                    $product = singleton::product($basketProduct->productId);
                    $category = singleton::category($basketProduct->categoryId);
                    $brand = singleton::brand($basketProduct->brandId);
                    $object = new stdClass();
                    $object->id = (int)$basketProduct->productId;
                    $object->quantity = $basketProduct->quantity;
                    $object->name = $product->product_name;
                    $object->category = $category->category_name;
                    $object->brand = $brand->brand_name;
                    $object->price = $basketProduct->price;
                    ?>
                    ga('ec:addProduct', <?= json_encode($object) ?>);
                    <? } ?>
                    ga('send', 'event', 'Checkout', 'main_site');
                });
            });
        </script>
    </div>
    <? view::show_blocks("col-xs-4") ?>
</div>
