<?
/**
 * @var ob_basket $basket
 */
?>
<div id="CreditCardPayment">
    <h2>Kredi Kartı veya Banka Kartı ile Öde</h2>
    <div id="CreditCardError" style="display: none">
        <div class="alert alert-danger"></div>
    </div>
    <form id="chargeForm" method="post" action="/checkout/charge">
        <input type="hidden" name="form" value="checkout-creditcard"> <input type="hidden" name="basket_total_cost" id="basket_total_cost_input"
            value="<?= $basket->sumAmount() ?>">
        <input type="hidden" name="selected_installment_id" value="0" id="selected_installment_id"> <input type="hidden" name="force_3d_secure" value="0" id="force_3d_secure">
        <div class="clearfix">
            <div class="col-xs-6">
                <div class="clearfix">
                    <div class="form-group has-feedback col-xs-12">
                        <label for="card_owner" class="control-label">Kart Üstündeki Ad Soyad</label>
                        <input id="card_owner" name="card_owner" type="text" class="form-control input-lg" autocomplete="off"/>
                        <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                    </div>
                </div>
                <div class="clearfix">
                    <div class="form-group has-feedback col-xs-12">
                        <label for="card_number" class="control-label">Kart Numarası</label> <input id="card_number" name="card_number" type="text" class="form-control input-lg"
                            autocomplete="off"/>
                        <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                    </div>
                </div>
                <div class="clearfix">
                    <div class="col-xs-7 form-group">
                        <label for="ccexpire_m" class="control-label">Son Kullanma Tarihi <span class="glyphicon" aria-hidden="true"></span></label>
                        <div class="row">
                            <div class="col-xs-5">
                                <select id="expire_month" name="expire_month" class="select form-control" style="padding:6px 3px;" title="Ay">
                                    <option value="AA">Ay</option>
                                    <option value="01">01</option>
                                    <option value="02">02</option>
                                    <option value="03">03</option>
                                    <option value="04">04</option>
                                    <option value="05">05</option>
                                    <option value="06">06</option>
                                    <option value="07">07</option>
                                    <option value="08">08</option>
                                    <option value="09">09</option>
                                    <option value="10">10</option>
                                    <option value="11">11</option>
                                    <option value="12">12</option>
                                </select>
                            </div>
                            <div class="col-xs-7">
                                <select id="expire_year" name="expire_year" class="select form-control" style="padding:6px 3px;" title="Yıl">
                                    <option value="YY">Yıl</option><?
                                    $maxyear = date('Y') + 20;
                                    for ($i = date('Y'); $i < $maxyear; $i++) {
                                        echo '<option value="' . $i . '">' . $i . '</option>';
                                    } // for
                                    ?></select>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-5">
                        <div class="form-group has-feedback">
                            <label for="cvc" class="control-label">Güvenlik Kodu</label> <input type="text" id="cvc" name="cvc" class="w40 form-control" maxlength="4"
                                autocomplete="off"/>
                            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                        </div>
                    </div>
                </div>
                <div id="Secure3D" class="checkbox col-xs-12">
                    <label><input type="checkbox" name="use_3d_secure" value="1"><strong>3D Secure kullanarak ödemek istiyorum</strong></label>
                </div>
            </div>
            <div class="col-xs-6">
                <div id="CardPreview" class="">
                    <div id="CardFaces">
                        <div class="front face">
                            <div class="Owner">AD SOYAD</div>
                            <div class="Number">0000 0000 0000 0000</div>
                            <div class="Expiry">AA/YY</div>
                            <div class="BrandImg"></div>
                            <div class="TypeImg"></div>
                            <div class="Cvc">0000</div>
                        </div>
                        <div class="back face center">
                            <div class="CvcPlace">XXXX <span class="Cvc">000</span></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="InstallmentOptions"></div>
    </form>
</div>
<div id="CreditCardProcessing" style="display: none">
    <h2>ÖDEME YAPILIYOR</h2>
    <div class="clearfix">
        <div class="col-xs-offset-2 col-xs-8">
            <div class="text-center b">Kredi kartınızdan <span class="totalChargeAmount"></span> çekim yapılıyor.</div>
            <div class="progress progress-striped active mt">
                <div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%"></div>
            </div>
        </div>
    </div>
    <div class="text-center">Siparişinizin sorunsuz tamamlanabilmesi için lütfen işlem tamamlanana kadar sayfadan ayrılmayın!</div>
</div>
<script type="text/javascript" src="/js/checkout.creditcard.js"></script>
