<?
/**
 * @var bank_accounts_model[] $bankAccounts
 * @var ob_basket $basket
 * @var string $wireTransferNotes
 */
?>
<div id="wireTransferPayment">
    <form id="wireTransferForm" method="post" action="/checkout/wireTransfer">
        <input type="hidden" name="form" value="checkout-payment"/> <input type="hidden" id="basket_total_cost_input" name="basket_total_cost" value="<?= $basket->sumAmount() ?>"/>
        <div style="font-size: 16px;">
            <strong>ALICI ADI:</strong> {FULL_COMPANY_NAME}
        </div>
        <a name="BankAccountList"></a>
        <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table table-striped mt" id="bankAccounts">
            <thead>
            <tr>
                <th></th>
                <th class="tabletd" valign="middle" style="width: 200px;"><strong>Banka</strong></th>
                <th class="tabletd" valign="middle"><strong>IBAN / Hesap Bilgisi</strong></th>
            </tr>
            </thead>
            <tbody>
            <? foreach ($bankAccounts as $bankAccount) { ?>
                <tr>
                    <td>
                        <input type="radio" style="margin-left: 10px;" value="<?= $bankAccount->account_id ?>" name="bank_account_id" id="bc<?= $bankAccount->account_id ?>">
                    </td>
                    <td><label for="bc<?= $bankAccount->account_id ?>"><img src="/img/bank_logo/wire-<?= $bankAccount->bank_id ?>.png"></label></td>
                    <td>
                        <label style="font-size: 15px; letter-spacing: 1px;" for="bc<?= $bankAccount->account_id ?>"><?= join(str_split($bankAccount->iban_number, 4),
                                " ") ?></label>
                        <label style="font-weight: 400;" for="bc<?= $bankAccount->account_id ?>"><?= $bankAccount->account_number ?></label>
                    </td>
                </tr>
            <? } ?>
            </tbody>
            <tfoot>
            <tr>
                <td colspan="4" height="1" style="padding:0"></td>
            </tr>
            </tfoot>
        </table>
        <? if (!empty($wireTransferNotes)) { ?>
            <div class="well" id="moneyTransferInfo">
                <?= $wireTransferNotes ?>
            </div>
        <? } ?>
    </form>
</div>
<script type="text/javascript" src="/js/checkout.wiretransfer.js"></script>
<script type="text/javascript"></script>
