<div class="text-center mb">
    <h3 style="font-size: 30px;">Üzgünüz, Aradığınız Sayfa Bulunamadı.</h3>
    <div>
        Aradığınız sayfa taşınmış, silinmiş veya geçerliliğini yitirmiş olabilir.<br><br>
        Sayfanın üstündeki arama kutusuna ulaşmak istediğiniz içeriği yazarak doğru sayfaya ulaşmayı deneyebilir <br>veya aşağıdaki butona tıklayarak anasayfaya dönebilirsiniz.
    </div>
    <img alt="Aradığınız Sayfa Bulunamadı" src="/img/not-found.jpg">
    <div>
        <a class="btn btn-warning btn-lg mt mb" role="button" href="/"><i class="glyphicon glyphicon-chevron-left"></i> Anasayfaya Dön</a>
    </div>
</div>
