<?
/**
 * @var DataGridRow[] $data
 * @var string $idField
 * @var string $type
 * @var string $title
 * @var string $gridId
 * @var array[] $buttons
 * @var string $info
 * @var array $header
 * @var bool $hasAction
 * @var int $totalResult
 * @var int $activePage
 * @var int $totalPage
 * @var string $requestUri
 * @var string $formAction
 * @var string $formMethod
 */
?>
<? if ($type == DataGrid::TYPE_FORM) { ?>
<form action="<?= $formAction ?>" method="<?= $formMethod ?>" class="form-horizontal">
    <input type="hidden" name="id" value="<?= $gridId ?>">
    <? } ?>
    <section id="widget-grid" class="">
        <div class="row">
            <article class="col-xs-12">
                <div class="jarviswidget jarviswidget-color-darken" id="<?= $gridId ?>" data-widget-colorbutton="false" data-widget-sortable="false" data-widget-editbutton="false"
                    data-widget-togglebutton="false" data-widget-deletebutton="false">
                    <header>
                        <span class="widget-icon"> <i class="fa fa-table"></i> </span>
                        <h2><?= $title ?></h2>
                        <? if ($buttons) { ?>
                            <div class="widget-toolbar" role="menu">
                                <? foreach ($buttons as $button) { ?>
                                    <a href="<?= $button['link'] ?>" class="btn btn-<?= $button['type'] ?>">
                                        <? if ($button['icon']) { ?>
                                            <i class="fa <?= $button['icon'] ?>"></i>
                                        <? } ?>
                                        <?= $button['title'] ?>
                                    </a>
                                <? } ?>
                            </div>
                        <? } ?>
                    </header>
                    <div class="tableContent">
                        <div class="widget-body no-padding">
                            <? if ($info) { ?>
                                <div class="alert alert-info no-margin fade in">
                                    <button class="close" data-dismiss="alert">×</button>
                                    <i class="fa-fw fa fa-info"></i>
                                    <?= $info ?>>
                                </div>
                            <? } ?>
                            <div class="table-responsive">
                                <table class="table table-hover table-striped" <?= $idField ? "data-idfield='" . $idField . "'" : '' ?>>
                                    <thead>
                                    <tr>
                                        <? foreach ($header as $key => $headerData) {
                                            $attr = $headerData;
                                            unset($attr['header']);
                                            unset($attr['type']);
                                            unset($attr['table']);
                                            unset($attr['formOptions']);
                                            unset($attr['classes']);
                                            unset($attr['text']);
                                            $attrText = array();
                                            foreach ($attr as $index => $item) {
                                                $attrText [] = "$index='$item'";
                                            }
                                            ?>
                                            <th <?= implode(' ', $attrText) ?> ><?= $headerData['header'] ?></th>
                                        <? } ?>
                                        <? if ($hasAction) { ?>
                                            <th></th>
                                        <? } ?>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <? foreach ($data as $key => $row) { ?>
                                        <tr<?= (!empty($row->background) ? ' class="' . $row->background . '"' : '') ?> <?= $idField ? "data-$idField='" . $row->data[$idField] . "'" : '' ?>>
                                            <? if ($type == DataGrid::TYPE_FORM && $idField) { ?>
                                                <input type="hidden" name="<?= $idField ?>[]" value="<?= $row->data[$idField] ?>"/>
                                            <? } ?>
                                            <? foreach ($header as $headerKey => $headerData) { ?>
                                                <td class="<?= isset($headerData['class']) ? $headerData['class'] : '' ?>" data-name="<?= $headerKey ?>">
                                                    <?= isset($row->data[$headerKey]) ? $row->data[$headerKey] : '' ?>
                                                </td>
                                            <? } ?>
                                            <? if ($hasAction) { ?>
                                                <td class="text-right">
                                                    <? if ($row->actions) { ?>
                                                        <? foreach ($row->actions as $action) {
                                                            $classes = array("btn-" . $action->buttonClass);
                                                            if ($action->confirm) {
                                                                $classes[] = "requireConfirm";
                                                            }
                                                            if ($action->type == 'popup') {
                                                                $classes[] = "ajaxPopup";
                                                            }
                                                            ?>
                                                            <a href="<?= $action->link ?>" class="btn btn-xs <?= implode(" ", $classes) ?>"> <span
                                                                    class="glyphicon  <?= $action->icon ?>"></span>
                                                                <?= $action->title ?>
                                                            </a>
                                                        <? } ?>
                                                    <? } ?>
                                                </td>
                                            <? } ?>
                                        </tr>
                                    <? } ?>
                                    </tbody>
                                </table>
                                <div class="dt-toolbar-footer">
                                    <div class="col-xs-12 hidden-xs">
                                        <div class="dataTables_info" id="datatable_tabletools_info" role="status" aria-live="polite">
                                            <? if ($totalResult > 0) { ?>
                                                Toplam <span class="text-primary"><?= $totalResult ?></span> kayıt
                                            <? } ?>
                                            <span id="loading" style="display: none">
                                            <i class="fa fa-refresh fa-spin"></i>
                                        </span>
                                        </div>
                                    </div>
                                    <? if ($type == DataGrid::TYPE_FORM) { ?>
                                        <div class="col-xs-6 text-right">
                                            <button class="btn btn-labeled btn-primary"><span class="btn-label"><i class="fa fa-save"></i></span>Kaydet</button>
                                        </div>
                                    <? } else { ?>
                                        <div class="col-xs-6">
                                            <div class="dataTables_paginate paging_simple_numbers" id="datatable_tabletools_paginate">
                                                <?= pagination::renderOasisPagination($activePage, $totalPage, $requestUri) ?>
                                            </div>
                                        </div>
                                    <? } ?>
                                </div>
                            </div>
                            <script type="text/javascript">
                                $(function () {
                                    $('.pagination li a').click(function () {
                                        var $this = $(this);
                                        var requestUri = $this.parents(".pagination").data('request-uri');
                                        var pageId = $this.data('page');
                                        $('#loading').show();
                                        $.ajax({
                                            type: "POST",
                                            url: requestUri.replace("__id__", pageId),
                                            data: OASIS.getPostParams(),
                                            success: function (content) {
                                                var response = $.parseJSON(content);
                                                response.Content = response.Content || "";
                                                if (response.Content != "") {
                                                    var newContent = $('<div />').html(response.Content).find('.tableContent').html();
                                                    var tableContent = $this.parents('.tableContent');
                                                    tableContent.html(newContent);
                                                    $('html, body').animate({
                                                        scrollTop: tableContent.parent().offset().top
                                                    }, 1);
                                                }
                                            }
                                        });
                                    });
                                    <? if( $idField ) { ?>
                                    $('a[data-rel="grid-switch-button"]').click(function (e) {
                                        e.preventDefault();
                                        var $this = $(this);
                                        if (!$this.hasClass('requireConfirm')) {
                                            $this.addClass("disabled");
                                            $this.children("span.btnIcon").addClass("fa-spin");
                                            var idField = $this.parents("table[data-idfield]").data("idfield");
                                            var data = OASIS.getPostParams($this.data());
                                            data.id = $this.parents("tr[data-" + idField + "]").data(idField);
                                            $.ajax({
                                                type: "POST",
                                                url: $this.data("href"),
                                                data: data
                                            }).done(function (response) {
                                                response.newStatus = response.newStatus || 0;
                                                if ($this.data('value') != response.newStatus) {
                                                    $this.addClass($this.attr("data-class-" + response.newStatus)).removeClass('' + $this.attr("data-class-" + $this.data('value')));
                                                    $this.data('value', response.newStatus);
                                                    $this.children("span.btnText").html($this.attr("data-text-" + response.newStatus));
                                                }
                                            }).fail(function () {
                                                alert("İşlem Başarısız");
                                            }).always(function () {
                                                $this.removeClass('disabled');
                                                $this.children("span.btnIcon").removeClass("fa-spin");
                                                if ($this.hasClass("confirmed")) {
                                                    $this.addClass("requireConfirm").removeClass("confirmed");
                                                }
                                            });
                                        }
                                    });
                                    <? } ?>
                                });
                            </script>
                        </div>
                    </div>
                </div>
            </article>
        </div>
    </section>
    <? if ($type == DataGrid::TYPE_FORM) { ?>
</form>
<? } ?>
