<?
/**
 * @var string $themeDir
 */
?>
<div class="header">
    <div class="headerTop container">
        <div class="row">
            <div class="col-xs-3">
                <a href="<?= app::getUrl(ACTIVE_APP, "http") ?>" title="Logo"><img src="<?= $themeDir ?>/img/logo.png" alt="<?= app::getName() ?>" height="75"></a>
            </div>
            <div class="col-xs-9">
                <div class="headerHelp clearfix">
                    <div class="pull-right">
                        <? if (session::isMember()) { ?>
                            <ul class="userMenu">
                                <li class="dropdown"><a role="button" class="dropdown-toggle" href="javascript:" data-toggle="dropdown" aria-haspopup="true"
                                        aria-expanded="false">Hesabım [<?= mb_strtoupper(session::get("firstName")) ?>] <span class="caret"></span> </a>
                                    <ul class="dropdown-menu">
                                        <li><a href="<?= app::getUrl(ACTIVE_APP, "http") ?>/account/details"><i class="glyphicon glyphicon-user"></i> Kişisel Bilgilerim</a></li>
                                        <li><a href="<?= app::getUrl(ACTIVE_APP, "http") ?>/account/addresses"><i class="glyphicon glyphicon-list-alt"></i> Adreslerim</a></li>
                                        <li><a href="<?= app::getUrl(ACTIVE_APP, "http") ?>/account/shopping_checks"><i class="glyphicon glyphicon-tag"></i> Alışveriş Çeklerim</a>
                                        </li>
                                        <li role="separator" class="divider"></li>
                                        <li><a href="<?= app::getUrl(ACTIVE_APP, "http") ?>/siparis-takip"><i class="glyphicon glyphicon-ok"></i> Siparişlerim</a></li>
                                        <li><a href="<?= app::getUrl(ACTIVE_APP, "http") ?>/order/defectreturn"><i class="glyphicon glyphicon-refresh"></i> Arıza/İade Bildirimi</a>
                                        </li>
                                        <li><a href="<?= app::getUrl(ACTIVE_APP, "http") ?>/support/tickets"><i class="glyphicon glyphicon-comment"></i> Destek Taleplerim</a></li>
                                        <li><a href="<?= app::getUrl(ACTIVE_APP, "http") ?>/support/request"><i class="glyphicon glyphicon-plus-sign"></i> Yeni Talep Oluştur</a>
                                        </li>
                                        <li role="separator" class="divider"></li>
                                        <li><a href="<?= app::getUrl(ACTIVE_APP, "http") ?>/member/logout"><i class="glyphicon glyphicon-send"></i> Çıkış Yap</a>
                                        </li>
                                    </ul>
                                </li>
                                <li><a role="button" href="<?= app::getUrl(ACTIVE_APP, "http") ?>/siparis-takip">Sipariş Takip</a></li>
                                <li><a role="button" href="<?= app::getUrl(ACTIVE_APP, "http") ?>/iletisim">Bize Ulaşın</a></li>
                            </ul>
                        <? } else { ?>
                            <ul class="userMenu">
                                <li><a role="button" class="signup-required" href="javascript:">Üye Ol</a></li>
                                <li><a role="button" class="login-required" href="javascript:">Giriş Yap</a></li>
                                <li><a role="button" class="login-required" href="<?= app::getUrl(ACTIVE_APP, "http") ?>/siparis-takip">Sipariş Takip</a></li>
                                <li><a role="button" href="<?= app::getUrl(ACTIVE_APP, "http") ?>/iletisim">Bize Ulaşın</a></li>
                            </ul>
                        <? } ?>
                    </div>
                </div>
                <div class="row headerSearchCart">
                    <div class="col-xs-9">
                        <div class="search">
                            <form id="search" action="/ara">
                                <div class="input-group">
                                    <?= menu::generateSearchCategoryMenu() ?>
                                    <input type="text" name="q" id="searchQuery" value="" class="form-control" placeholder="aradığınız ürün">
                                    <span class="input-group-btn"><a href="javascript:" onclick="$('form#search').submit();" class="searchButton"><i
                                                class="glyphicon glyphicon-search"></i></a></span>
                                </div>
                                <input type="hidden" id="search-category" name="categoryId" value="0">
                            </form>
                        </div>
                    </div>
                    <div class="col-xs-3">
                        <a title="Alışveriş Sepetim" class="btn btn-warning btn-md pull-right" id="cartButton" href="<?= app::getUrl(ACTIVE_APP, "http") ?>/cart">
                            <span class="badge cartItems pull-right"><?= intval(session::getCartProductCount()) ?></span> SEPETİM </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
