<?
/**
 * @var string $formAction
 * @var array $formParameters
 */
?>
<form id="SecurePaymentForm" action="<?= $formAction ?>" target="SecurePaymentFrame" method="POST">
    <? foreach ($formParameters as $key => $value) { ?>
        <input type="hidden" name="<?= $key ?>" value="<?= htmlspecialchars($value, ENT_COMPAT) ?>">
    <? } ?>
</form>
<iframe name="SecurePaymentFrame" width="100%" height="700" frameborder="0"></iframe>
<script type="text/javascript">
    setTimeout(function () {
        document.getElementById("SecurePaymentForm").submit();
    }, 100);
</script>
